/*
 * Copyright (2021) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ***********************************************************************************
// * This file is automatically generated. Manual modification is not allowed.       *
// * There is a unit test that should prevent merging a manual change.               *
// *                                                                                 *
// * To make changes to the suites, modify the generator script config at            *
// * SuiteGeneratorConfig.scala and run it. The generator can be run via the         *
// * sbt command deltaSuiteGenerator / run.                                          *
// *                                                                                 *
// * DO NOT TOUCH ANYTHING IN THIS FILE!                                             *
// ***********************************************************************************

package org.apache.spark.sql.delta.generatedsuites

import org.apache.spark.sql.delta._
import org.apache.spark.sql.delta.cdc._
import org.apache.spark.sql.delta.rowid._

class DeleteScalaTestsDeleteScalaSuite extends DeleteScalaTests with DeleteScalaMixin
class DeleteBaseTestsDeleteScalaSuite extends DeleteBaseTests with DeleteScalaMixin

class DeleteCDCTestsDeleteSQLDeltaDMLTestUtilsPathBasedCDCEnabledSuite
  extends DeleteCDCTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with CDCEnabled
  with DeleteCDCMixin

class DeleteSQLTestsDeleteSQLDeltaDMLTestUtilsNameBasedSuite
  extends DeleteSQLTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsNameBased

class DeleteSQLTestsDeleteSQLDeltaDMLTestUtilsPathBasedSuite
  extends DeleteSQLTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased

class DeleteSQLTestsDeleteSQLDeltaDMLTestUtilsPathBasedDeltaColumnMappingEnableIdModeSuite
  extends DeleteSQLTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with DeltaColumnMappingEnableIdMode

class DeleteSQLTestsDeleteSQLDeltaDMLTestUtilsPathBasedDeltaColumnMappingEnableNameModeSuite
  extends DeleteSQLTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with DeltaColumnMappingEnableNameMode
  with DeleteSQLNameColumnMappingMixin

class DeleteSQLTestsDeleteSQLDeltaDMLTestUtilsPathBasedDeleteSQLWithDeletionVectorsPrediSFURCIYSuite
  extends DeleteSQLTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with DeleteSQLWithDeletionVectorsMixin
  with PredicatePushdownDisabled

class DeleteSQLTestsDeleteSQLDeltaDMLTestUtilsPathBasedDeleteSQLWithDeletionVectorsPrediNRMUHXQSuite
  extends DeleteSQLTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with DeleteSQLWithDeletionVectorsMixin
  with PredicatePushdownEnabled

class DeleteSQLTestsDeleteSQLDeltaDMLTestUtilsPathBasedCDCEnabledSuite
  extends DeleteSQLTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with CDCEnabled
  with DeleteCDCMixin

class DeleteTempViewTestsDeleteSQLDeltaDMLTestUtilsNameBasedSuite
  extends DeleteTempViewTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsNameBased

class DeleteTempViewTestsDeleteSQLDeltaDMLTestUtilsPathBasedSuite
  extends DeleteTempViewTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased

class DeleteTempViewTestsDeleteSQLDeltaDMLTestUtilsPathBasedDeltaColumnMappingEnableIdModeSuite
  extends DeleteTempViewTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with DeltaColumnMappingEnableIdMode

class DeleteTempViewTestsDeleteSQLDeltaDMLTestUtilsPathBasedDeltaColumnMappingEnableNameModeSuite
  extends DeleteTempViewTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with DeltaColumnMappingEnableNameMode
  with DeleteSQLNameColumnMappingMixin

class DeleteTempViewTestsDeleteSQLDeltaDMLTestUtilsPathBasedDeleteSQLWithDeletionVectorsUF4SBZASuite
  extends DeleteTempViewTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with DeleteSQLWithDeletionVectorsMixin
  with PredicatePushdownDisabled

class DeleteTempViewTestsDeleteSQLDeltaDMLTestUtilsPathBasedDeleteSQLWithDeletionVectorsTHW2KHASuite
  extends DeleteTempViewTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with DeleteSQLWithDeletionVectorsMixin
  with PredicatePushdownEnabled

class DeleteTempViewTestsDeleteSQLDeltaDMLTestUtilsPathBasedCDCEnabledSuite
  extends DeleteTempViewTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with CDCEnabled
  with DeleteCDCMixin

class DeleteBaseTestsDeleteSQLDeltaDMLTestUtilsNameBasedSuite
  extends DeleteBaseTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsNameBased

class DeleteBaseTestsDeleteSQLDeltaDMLTestUtilsPathBasedSuite
  extends DeleteBaseTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased

class DeleteBaseTestsDeleteSQLDeltaDMLTestUtilsPathBasedDeltaColumnMappingEnableIdModeSuite
  extends DeleteBaseTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with DeltaColumnMappingEnableIdMode

class DeleteBaseTestsDeleteSQLDeltaDMLTestUtilsPathBasedDeltaColumnMappingEnableNameModeSuite
  extends DeleteBaseTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with DeltaColumnMappingEnableNameMode
  with DeleteSQLNameColumnMappingMixin

class DeleteBaseTestsDeleteSQLDeltaDMLTestUtilsPathBasedDeleteSQLWithDeletionVectorsPredAPDVT7YSuite
  extends DeleteBaseTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with DeleteSQLWithDeletionVectorsMixin
  with PredicatePushdownDisabled

class DeleteBaseTestsDeleteSQLDeltaDMLTestUtilsPathBasedDeleteSQLWithDeletionVectorsPredFAFSNSYSuite
  extends DeleteBaseTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with DeleteSQLWithDeletionVectorsMixin
  with PredicatePushdownEnabled

class DeleteBaseTestsDeleteSQLDeltaDMLTestUtilsPathBasedCDCEnabledSuite
  extends DeleteBaseTests
  with DeleteSQLMixin
  with DeltaDMLTestUtilsPathBased
  with CDCEnabled
  with DeleteCDCMixin

class RowTrackingDeleteSuiteBasePersistentDVDisabledSuite
  extends RowTrackingDeleteSuiteBase
  with PersistentDVDisabled

class RowTrackingDeleteSuiteBasePersistentDVEnabledSuite
  extends RowTrackingDeleteSuiteBase
  with PersistentDVEnabled

class RowTrackingDeleteSuiteBaseCDCEnabledPersistentDVDisabledSuite
  extends RowTrackingDeleteSuiteBase
  with CDCEnabled
  with PersistentDVDisabled

class RowTrackingDeleteSuiteBaseCDCEnabledPersistentDVEnabledSuite
  extends RowTrackingDeleteSuiteBase
  with CDCEnabled
  with PersistentDVEnabled

class RowTrackingDeleteSuiteBasePersistentDVDisabledDeltaColumnMappingEnableIdModeSuite
  extends RowTrackingDeleteSuiteBase
  with PersistentDVDisabled
  with DeltaColumnMappingEnableIdMode

class RowTrackingDeleteSuiteBasePersistentDVDisabledDeltaColumnMappingEnableNameModeSuite
  extends RowTrackingDeleteSuiteBase
  with PersistentDVDisabled
  with DeltaColumnMappingEnableNameMode

class RowTrackingDeleteSuiteBaseCDCEnabledPersistentDVEnabledDeltaColumnMappingEnableIdModeSuite
  extends RowTrackingDeleteSuiteBase
  with CDCEnabled
  with PersistentDVEnabled
  with DeltaColumnMappingEnableIdMode

class RowTrackingDeleteSuiteBaseCDCEnabledPersistentDVEnabledDeltaColumnMappingEnableNameModeSuite
  extends RowTrackingDeleteSuiteBase
  with CDCEnabled
  with PersistentDVEnabled
  with DeltaColumnMappingEnableNameMode

class RowTrackingDeleteDvBasePersistentDVEnabledSuite
  extends RowTrackingDeleteDvBase
  with PersistentDVEnabled

class RowTrackingDeleteDvBaseCDCEnabledPersistentDVEnabledSuite
  extends RowTrackingDeleteDvBase
  with CDCEnabled
  with PersistentDVEnabled

class RowTrackingDeleteDvBaseCDCEnabledPersistentDVEnabledDeltaColumnMappingEnableIdModeSuite
  extends RowTrackingDeleteDvBase
  with CDCEnabled
  with PersistentDVEnabled
  with DeltaColumnMappingEnableIdMode

class RowTrackingDeleteDvBaseCDCEnabledPersistentDVEnabledDeltaColumnMappingEnableNameModeSuite
  extends RowTrackingDeleteDvBase
  with CDCEnabled
  with PersistentDVEnabled
  with DeltaColumnMappingEnableNameMode
