/*
 * Copyright (2021) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ***********************************************************************************
// * This file is automatically generated. Manual modification is not allowed.       *
// * There is a unit test that should prevent merging a manual change.               *
// *                                                                                 *
// * To make changes to the suites, modify the generator script config at            *
// * SuiteGeneratorConfig.scala and run it. The generator can be run via the         *
// * sbt command deltaSuiteGenerator / run.                                          *
// *                                                                                 *
// * DO NOT TOUCH ANYTHING IN THIS FILE!                                             *
// ***********************************************************************************

package org.apache.spark.sql.delta.generatedsuites

import org.apache.spark.sql.delta._
import org.apache.spark.sql.delta.cdc._
import org.apache.spark.sql.delta.deletionvectors._
import org.apache.spark.sql.delta.rowid._
import org.apache.spark.sql.delta.rowtracking._

class MergeIntoScalaTestsMergeIntoScalaSuite extends MergeIntoScalaTests with MergeIntoScalaMixin
class MergeIntoBasicTestsMergeIntoScalaSuite extends MergeIntoBasicTests with MergeIntoScalaMixin

class MergeIntoNestedDataTestsMergeIntoScalaSuite
  extends MergeIntoNestedDataTests
  with MergeIntoScalaMixin

class MergeIntoUnlimitedMergeClausesTestsMergeIntoScalaSuite
  extends MergeIntoUnlimitedMergeClausesTests
  with MergeIntoScalaMixin

class MergeIntoSuiteBaseMiscTestsMergeIntoScalaSuite
  extends MergeIntoSuiteBaseMiscTests
  with MergeIntoScalaMixin

class MergeIntoNotMatchedBySourceMergeIntoScalaSuite
  extends MergeIntoNotMatchedBySourceSuite
  with MergeIntoScalaMixin

class MergeIntoSchemaEvolutionAllTestsMergeIntoScalaSuite
  extends MergeIntoSchemaEvolutionAllTests
  with MergeIntoScalaMixin

class MergeIntoSQLTestsMergeIntoSQLSuite extends MergeIntoSQLTests with MergeIntoSQLMixin

class MergeIntoSQLTestsMergeIntoSQLDeltaColumnMappingEnableIdModeMergeIntoSQLColumnMappiE3VOO7QSuite
  extends MergeIntoSQLTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableIdMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoSQLTestsMergeIntoSQLDeltaColumnMappingEnableNameModeMergeIntoSQLColumnMap63M5YPASuite
  extends MergeIntoSQLTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableNameMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoSQLNondeterministicOrderTestsMergeIntoSQLSuite
  extends MergeIntoSQLNondeterministicOrderTests
  with MergeIntoSQLMixin

class MergeIntoSQLNondeterministicOrderTestsMergeIntoSQLDeltaColumnMappingEnableIdModeMeET6765QSuite
  extends MergeIntoSQLNondeterministicOrderTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableIdMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoSQLNondeterministicOrderTestsMergeIntoSQLDeltaColumnMappingEnableNameModeSK4YN4YSuite
  extends MergeIntoSQLNondeterministicOrderTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableNameMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoBasicTestsMergeIntoSQLSuite extends MergeIntoBasicTests with MergeIntoSQLMixin

class MergeIntoBasicTestsMergeIntoSQLDeltaColumnMappingEnableIdModeMergeIntoSQLColumnMap3ITXYDASuite
  extends MergeIntoBasicTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableIdMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoBasicTestsMergeIntoSQLDeltaColumnMappingEnableNameModeMergeIntoSQLColumnMSUPDQJYSuite
  extends MergeIntoBasicTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableNameMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoTempViewsTestsMergeIntoSQLSuite
  extends MergeIntoTempViewsTests
  with MergeIntoSQLMixin

class MergeIntoTempViewsTestsMergeIntoSQLDeltaColumnMappingEnableIdModeMergeIntoSQLColumSZ7YUIISuite
  extends MergeIntoTempViewsTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableIdMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoTempViewsTestsMergeIntoSQLDeltaColumnMappingEnableNameModeMergeIntoSQLColSNANUYYSuite
  extends MergeIntoTempViewsTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableNameMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoNestedDataTestsMergeIntoSQLSuite
  extends MergeIntoNestedDataTests
  with MergeIntoSQLMixin

class MergeIntoNestedDataTestsMergeIntoSQLDeltaColumnMappingEnableIdModeMergeIntoSQLColu6YVXDZYSuite
  extends MergeIntoNestedDataTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableIdMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoNestedDataTestsMergeIntoSQLDeltaColumnMappingEnableNameModeMergeIntoSQLCoKJHCBWASuite
  extends MergeIntoNestedDataTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableNameMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoUnlimitedMergeClausesTestsMergeIntoSQLSuite
  extends MergeIntoUnlimitedMergeClausesTests
  with MergeIntoSQLMixin

class MergeIntoUnlimitedMergeClausesTestsMergeIntoSQLDeltaColumnMappingEnableIdModeMergePLXX5FASuite
  extends MergeIntoUnlimitedMergeClausesTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableIdMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoUnlimitedMergeClausesTestsMergeIntoSQLDeltaColumnMappingEnableNameModeMerK7DXPDASuite
  extends MergeIntoUnlimitedMergeClausesTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableNameMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoSuiteBaseMiscTestsMergeIntoSQLSuite
  extends MergeIntoSuiteBaseMiscTests
  with MergeIntoSQLMixin

class MergeIntoSuiteBaseMiscTestsMergeIntoSQLDeltaColumnMappingEnableIdModeMergeIntoSQLCK456OHASuite
  extends MergeIntoSuiteBaseMiscTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableIdMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoSuiteBaseMiscTestsMergeIntoSQLDeltaColumnMappingEnableNameModeMergeIntoSQE3RKDNQSuite
  extends MergeIntoSuiteBaseMiscTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableNameMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoNotMatchedBySourceMergeIntoSQLSuite
  extends MergeIntoNotMatchedBySourceSuite
  with MergeIntoSQLMixin

class MergeIntoNotMatchedBySourceMergeIntoSQLDeltaColumnMappingEnableIdModeMergeIntoSQLCT2RJUIQSuite
  extends MergeIntoNotMatchedBySourceSuite
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableIdMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoNotMatchedBySourceMergeIntoSQLDeltaColumnMappingEnableNameModeMergeIntoSQAWNMDZASuite
  extends MergeIntoNotMatchedBySourceSuite
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableNameMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoSchemaEvolutionAllTestsMergeIntoSQLSuite
  extends MergeIntoSchemaEvolutionAllTests
  with MergeIntoSQLMixin

class MergeIntoSchemaEvolutionAllTestsMergeIntoSQLDeltaColumnMappingEnableIdModeMergeIntWGLAUBQSuite
  extends MergeIntoSchemaEvolutionAllTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableIdMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoSchemaEvolutionAllTestsMergeIntoSQLDeltaColumnMappingEnableNameModeMergeIUCCZW6YSuite
  extends MergeIntoSchemaEvolutionAllTests
  with MergeIntoSQLMixin
  with DeltaColumnMappingEnableNameMode
  with MergeIntoSQLColumnMappingOverrides

class MergeIntoDVsTestsMergeIntoSQLMergeIntoDVsMergeIntoDVsOverridesSuite
  extends MergeIntoDVsTests
  with MergeIntoSQLMixin
  with MergeIntoDVsMixin
  with MergeIntoDVsOverrides

class MergeIntoDVsTestsMergeIntoSQLMergeIntoDVsWithPredicatePushdownSuite
  extends MergeIntoDVsTests
  with MergeIntoSQLMixin
  with MergeIntoDVsWithPredicatePushdownMixin

class MergeIntoSQLTestsMergeIntoSQLMergeIntoDVsMergeIntoDVsOverridesSuite
  extends MergeIntoSQLTests
  with MergeIntoSQLMixin
  with MergeIntoDVsMixin
  with MergeIntoDVsOverrides

class MergeIntoSQLTestsMergeIntoSQLMergeIntoDVsWithPredicatePushdownSuite
  extends MergeIntoSQLTests
  with MergeIntoSQLMixin
  with MergeIntoDVsWithPredicatePushdownMixin

class MergeIntoSQLNondeterministicOrderTestsMergeIntoSQLMergeIntoDVsMergeIntoDVsOverridesSuite
  extends MergeIntoSQLNondeterministicOrderTests
  with MergeIntoSQLMixin
  with MergeIntoDVsMixin
  with MergeIntoDVsOverrides

class MergeIntoSQLNondeterministicOrderTestsMergeIntoSQLMergeIntoDVsWithPredicatePushdownSuite
  extends MergeIntoSQLNondeterministicOrderTests
  with MergeIntoSQLMixin
  with MergeIntoDVsWithPredicatePushdownMixin

class MergeIntoBasicTestsMergeIntoSQLMergeIntoDVsMergeIntoDVsOverridesSuite
  extends MergeIntoBasicTests
  with MergeIntoSQLMixin
  with MergeIntoDVsMixin
  with MergeIntoDVsOverrides

class MergeIntoBasicTestsMergeIntoSQLMergeIntoDVsWithPredicatePushdownSuite
  extends MergeIntoBasicTests
  with MergeIntoSQLMixin
  with MergeIntoDVsWithPredicatePushdownMixin

class MergeIntoTempViewsTestsMergeIntoSQLMergeIntoDVsMergeIntoDVsOverridesSuite
  extends MergeIntoTempViewsTests
  with MergeIntoSQLMixin
  with MergeIntoDVsMixin
  with MergeIntoDVsOverrides

class MergeIntoTempViewsTestsMergeIntoSQLMergeIntoDVsWithPredicatePushdownSuite
  extends MergeIntoTempViewsTests
  with MergeIntoSQLMixin
  with MergeIntoDVsWithPredicatePushdownMixin

class MergeIntoNestedDataTestsMergeIntoSQLMergeIntoDVsMergeIntoDVsOverridesSuite
  extends MergeIntoNestedDataTests
  with MergeIntoSQLMixin
  with MergeIntoDVsMixin
  with MergeIntoDVsOverrides

class MergeIntoNestedDataTestsMergeIntoSQLMergeIntoDVsWithPredicatePushdownSuite
  extends MergeIntoNestedDataTests
  with MergeIntoSQLMixin
  with MergeIntoDVsWithPredicatePushdownMixin

class MergeIntoUnlimitedMergeClausesTestsMergeIntoSQLMergeIntoDVsMergeIntoDVsOverridesSuite
  extends MergeIntoUnlimitedMergeClausesTests
  with MergeIntoSQLMixin
  with MergeIntoDVsMixin
  with MergeIntoDVsOverrides

class MergeIntoUnlimitedMergeClausesTestsMergeIntoSQLMergeIntoDVsWithPredicatePushdownSuite
  extends MergeIntoUnlimitedMergeClausesTests
  with MergeIntoSQLMixin
  with MergeIntoDVsWithPredicatePushdownMixin

class MergeIntoSuiteBaseMiscTestsMergeIntoSQLMergeIntoDVsMergeIntoDVsOverridesSuite
  extends MergeIntoSuiteBaseMiscTests
  with MergeIntoSQLMixin
  with MergeIntoDVsMixin
  with MergeIntoDVsOverrides

class MergeIntoSuiteBaseMiscTestsMergeIntoSQLMergeIntoDVsWithPredicatePushdownSuite
  extends MergeIntoSuiteBaseMiscTests
  with MergeIntoSQLMixin
  with MergeIntoDVsWithPredicatePushdownMixin

class MergeIntoNotMatchedBySourceMergeIntoSQLMergeIntoDVsMergeIntoDVsOverridesSuite
  extends MergeIntoNotMatchedBySourceSuite
  with MergeIntoSQLMixin
  with MergeIntoDVsMixin
  with MergeIntoDVsOverrides

class MergeIntoNotMatchedBySourceMergeIntoSQLMergeIntoDVsWithPredicatePushdownSuite
  extends MergeIntoNotMatchedBySourceSuite
  with MergeIntoSQLMixin
  with MergeIntoDVsWithPredicatePushdownMixin

class MergeIntoSchemaEvolutionAllTestsMergeIntoSQLMergeIntoDVsMergeIntoDVsOverridesSuite
  extends MergeIntoSchemaEvolutionAllTests
  with MergeIntoSQLMixin
  with MergeIntoDVsMixin
  with MergeIntoDVsOverrides

class MergeIntoSchemaEvolutionAllTestsMergeIntoSQLMergeIntoDVsWithPredicatePushdownSuite
  extends MergeIntoSchemaEvolutionAllTests
  with MergeIntoSQLMixin
  with MergeIntoDVsWithPredicatePushdownMixin

class MergeCDCTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsMergeCDCWithDVsSuite
  extends MergeCDCTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsMixin
  with MergeCDCWithDVsMixin

class MergeCDCTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsWithPredicatePushdownMergeCVGFIZMASuite
  extends MergeCDCTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsWithPredicatePushdownMixin
  with MergeCDCWithDVsMixin

class MergeIntoDVsTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsMergeCDCWithDVsSuite
  extends MergeIntoDVsTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsMixin
  with MergeCDCWithDVsMixin

class MergeIntoDVsTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsWithPredicatePushdownMe2GGR2YYSuite
  extends MergeIntoDVsTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsWithPredicatePushdownMixin
  with MergeCDCWithDVsMixin

class MergeIntoSQLTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsMergeCDCWithDVsSuite
  extends MergeIntoSQLTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsMixin
  with MergeCDCWithDVsMixin

class MergeIntoSQLTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsWithPredicatePushdownMe5JLWDRYSuite
  extends MergeIntoSQLTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsWithPredicatePushdownMixin
  with MergeCDCWithDVsMixin

class MergeIntoSQLNondeterministicOrderTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsMeVMPBLEYSuite
  extends MergeIntoSQLNondeterministicOrderTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsMixin
  with MergeCDCWithDVsMixin

class MergeIntoSQLNondeterministicOrderTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsWiLH446PASuite
  extends MergeIntoSQLNondeterministicOrderTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsWithPredicatePushdownMixin
  with MergeCDCWithDVsMixin

class MergeIntoBasicTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsMergeCDCWithDVsSuite
  extends MergeIntoBasicTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsMixin
  with MergeCDCWithDVsMixin

class MergeIntoBasicTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsWithPredicatePushdownVNW3HNQSuite
  extends MergeIntoBasicTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsWithPredicatePushdownMixin
  with MergeCDCWithDVsMixin

class MergeIntoTempViewsTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsMergeCDCWithDVsSuite
  extends MergeIntoTempViewsTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsMixin
  with MergeCDCWithDVsMixin

class MergeIntoTempViewsTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsWithPredicatePushTPKJJCISuite
  extends MergeIntoTempViewsTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsWithPredicatePushdownMixin
  with MergeCDCWithDVsMixin

class MergeIntoNestedDataTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsMergeCDCWithDVsSuite
  extends MergeIntoNestedDataTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsMixin
  with MergeCDCWithDVsMixin

class MergeIntoNestedDataTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsWithPredicatePus4O7YOPYSuite
  extends MergeIntoNestedDataTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsWithPredicatePushdownMixin
  with MergeCDCWithDVsMixin

class MergeIntoUnlimitedMergeClausesTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsMergeZ75HJ4QSuite
  extends MergeIntoUnlimitedMergeClausesTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsMixin
  with MergeCDCWithDVsMixin

class MergeIntoUnlimitedMergeClausesTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsWithP7GEKCBQSuite
  extends MergeIntoUnlimitedMergeClausesTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsWithPredicatePushdownMixin
  with MergeCDCWithDVsMixin

class MergeIntoSuiteBaseMiscTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsMergeCDCWithDVsSuite
  extends MergeIntoSuiteBaseMiscTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsMixin
  with MergeCDCWithDVsMixin

class MergeIntoSuiteBaseMiscTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsWithPredicateVW425VASuite
  extends MergeIntoSuiteBaseMiscTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsWithPredicatePushdownMixin
  with MergeCDCWithDVsMixin

class MergeIntoNotMatchedBySourceMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsMergeCDCWithDVsSuite
  extends MergeIntoNotMatchedBySourceSuite
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsMixin
  with MergeCDCWithDVsMixin

class MergeIntoNotMatchedBySourceMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsWithPredicate4XPA7GISuite
  extends MergeIntoNotMatchedBySourceSuite
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsWithPredicatePushdownMixin
  with MergeCDCWithDVsMixin

class MergeIntoSchemaEvolutionAllTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsMergeCDCWithDVsSuite
  extends MergeIntoSchemaEvolutionAllTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsMixin
  with MergeCDCWithDVsMixin

class MergeIntoSchemaEvolutionAllTestsMergeIntoSQLCDCEnabledMergeCDCMergeIntoDVsWithPredEPXSK2YSuite
  extends MergeIntoSchemaEvolutionAllTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
  with MergeIntoDVsWithPredicatePushdownMixin
  with MergeCDCWithDVsMixin

class MergeCDCTestsMergeIntoSQLCDCEnabledMergeCDCSuite
  extends MergeCDCTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin

class MergeIntoSQLTestsMergeIntoSQLCDCEnabledMergeCDCSuite
  extends MergeIntoSQLTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin

class MergeIntoSQLNondeterministicOrderTestsMergeIntoSQLCDCEnabledMergeCDCSuite
  extends MergeIntoSQLNondeterministicOrderTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin

class MergeIntoBasicTestsMergeIntoSQLCDCEnabledMergeCDCSuite
  extends MergeIntoBasicTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin

class MergeIntoTempViewsTestsMergeIntoSQLCDCEnabledMergeCDCSuite
  extends MergeIntoTempViewsTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin

class MergeIntoNestedDataTestsMergeIntoSQLCDCEnabledMergeCDCSuite
  extends MergeIntoNestedDataTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin

class MergeIntoUnlimitedMergeClausesTestsMergeIntoSQLCDCEnabledMergeCDCSuite
  extends MergeIntoUnlimitedMergeClausesTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin

class MergeIntoSuiteBaseMiscTestsMergeIntoSQLCDCEnabledMergeCDCSuite
  extends MergeIntoSuiteBaseMiscTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin

class MergeIntoNotMatchedBySourceMergeIntoSQLCDCEnabledMergeCDCSuite
  extends MergeIntoNotMatchedBySourceSuite
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin

class MergeIntoSchemaEvolutionAllTestsMergeIntoSQLCDCEnabledMergeCDCSuite
  extends MergeIntoSchemaEvolutionAllTests
  with MergeIntoSQLMixin
  with CDCEnabled
  with MergeCDCMixin
