/*
 * Copyright (2021) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import sbt._
import sbt.Keys._
import xsbti.compile.CompileAnalysis

import org.scalafmt.sbt.ScalafmtPlugin.autoImport._
import com.lightbend.sbt.JavaFormatterPlugin.autoImport._
import com.jsuereth.sbtpgp.PgpKeys
import com.jsuereth.sbtpgp.SbtPgp.autoImport._
import sbtrelease.ReleasePlugin.autoImport._
import xerial.sbt.Sonatype.autoImport._

import Unidoc._

/**
 * Common settings and version constants shared across all modules.
 * This is the single source of truth for these values - build.sbt imports from here.
 */
object CommonSettings {

  // ============================================================
  // Scala versions
  // ============================================================
  val scala213 = "2.13.17"
  val all_scala_versions = Seq(scala213)
  val default_scala_version = settingKey[String]("Default Scala version")

  // ============================================================
  // Dependency version constants
  // ============================================================
  val scalaTestVersion = "3.2.15"
  val scalaTestVersionForConnectors = "3.0.8"
  val hadoopVersion = "3.4.2"
  val parquet4sVersion = "1.9.4"
  val protoVersion = "3.25.1"
  val grpcVersion = "1.62.2"
  def defaultSparkVersion: String = SparkVersionSpec.DEFAULT.fullVersion

  // ============================================================
  // JVM settings
  // ============================================================
  val targetJvm = settingKey[String]("Target JVM version")
  lazy val javaVersion: String = sys.props.getOrElse("java.version", "Unknown")
  lazy val javaVersionInt: Int = javaVersion.split("\\.")(0).toInt

  // ============================================================
  // Code formatting settings
  // ============================================================

  /** Enforce java code style on compile. */
  def javafmtCheckSettings: Seq[Def.Setting[Task[CompileAnalysis]]] = Seq(
    (Compile / compile) := ((Compile / compile) dependsOn (Compile / javafmtCheckAll)).value
  )

  /** Enforce scala code style on compile. */
  def scalafmtCheckSettings: Seq[Def.Setting[Task[CompileAnalysis]]] = Seq(
    (Compile / compile) := ((Compile / compile) dependsOn (Compile / scalafmtCheckAll)).value,
  )

  // ============================================================
  // Common project settings
  // ============================================================

  /**
   * Common settings applied to all projects.
   */
  lazy val commonSettings: Seq[Setting[_]] = Seq(
    organization := "io.delta",
    scalaVersion := default_scala_version.value,
    crossScalaVersions := all_scala_versions,
    fork := true,
    scalacOptions ++= Seq("-Ywarn-unused:imports"),
    javacOptions ++= {
      if (javaVersion.startsWith("1.8")) {
        Seq.empty // `--release` is supported since JDK 9 and the minimum supported JDK is 8
      } else {
        Seq("--release", targetJvm.value) // generated bytecode should be usable with JVM 1.8
      }
    },

    // Make sure any tests in any project that uses Spark is configured for running well locally
    Test / javaOptions ++= Seq(
      "-Dspark.ui.enabled=false",
      "-Dspark.ui.showConsoleProgress=false",
      "-Dspark.databricks.delta.snapshotPartitions=2",
      "-Dspark.sql.shuffle.partitions=5",
      "-Ddelta.log.cacheSize=3",
      "-Dspark.databricks.delta.delta.log.cacheSize=3",
      "-Dspark.sql.sources.parallelPartitionDiscovery.parallelism=5",
      "-Xmx1024m"
    ) ++ {
      if (javaVersionInt >= 17) {
        Seq(  // For Java 17 +
          "--add-opens=java.base/java.nio=ALL-UNNAMED",
          "--add-opens=java.base/java.lang=ALL-UNNAMED",
          "--add-opens=java.base/java.net=ALL-UNNAMED",
          "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED",
          "--add-opens=java.base/sun.util.calendar=ALL-UNNAMED"
        )
      } else {
        Seq.empty
      }
    },

    testOptions += Tests.Argument("-oF"),

    // Unidoc settings: by default dont document any source file
    unidocSourceFilePatterns := Nil,
  )

  // ============================================================
  // Release settings
  // ============================================================

  /**
   * Settings for modules that should not be published.
   */
  lazy val skipReleaseSettings: Seq[Setting[_]] = Seq(
    publishArtifact := false,
    publish / skip := true
  )

  /**
   * Release settings for artifact that contains only Java source code.
   */
  lazy val javaOnlyReleaseSettings: Seq[Setting[_]] = releaseSettings ++ Seq(
    // drop off Scala suffix from artifact names
    crossPaths := false,

    // we publish jars for each scalaVersion in crossScalaVersions. however, we only need to publish
    // one java jar. thus, only do so when the current scala version == default scala version
    publishArtifact := {
      val (expMaj, expMin, _) = Mima.getMajorMinorPatch(default_scala_version.value)
      s"$expMaj.$expMin" == scalaBinaryVersion.value
    },

    // exclude scala-library from dependencies in generated pom.xml
    autoScalaLibrary := false,
  )

  /**
   * Common release settings for published artifacts.
   */
  lazy val releaseSettings: Seq[Setting[_]] = Seq(
    publishMavenStyle := true,
    publishArtifact := true,
    Test / publishArtifact := false,
    releasePublishArtifactsAction := PgpKeys.publishSigned.value,
    releaseCrossBuild := true,
    pgpPassphrase := sys.env.get("PGP_PASSPHRASE").map(_.toArray),

    sonatypeProfileName := "io.delta",
    credentials += Credentials(
      "OSSRH Staging API Service",
      "ossrh-staging-api.central.sonatype.com",
      sys.env.getOrElse("SONATYPE_USERNAME", ""),
      sys.env.getOrElse("SONATYPE_PASSWORD", "")
    ),
    publishTo := {
      val ossrhBase = "https://ossrh-staging-api.central.sonatype.com/"
      if (isSnapshot.value) {
        Some("snapshots" at ossrhBase + "content/repositories/snapshots")
      } else {
        Some("releases"  at ossrhBase + "service/local/staging/deploy/maven2")
      }
    },
    licenses += ("Apache-2.0", url("http://www.apache.org/licenses/LICENSE-2.0")),
    pomExtra :=
      <url>https://delta.io/</url>
        <scm>
          <url>git@github.com:delta-io/delta.git</url>
          <connection>scm:git:git@github.com:delta-io/delta.git</connection>
        </scm>
        <developers>
          <developer>
            <id>marmbrus</id>
            <name>Michael Armbrust</name>
            <url>https://github.com/marmbrus</url>
          </developer>
          <developer>
            <id>brkyvz</id>
            <name>Burak Yavuz</name>
            <url>https://github.com/brkyvz</url>
          </developer>
          <developer>
            <id>jose-torres</id>
            <name>Jose Torres</name>
            <url>https://github.com/jose-torres</url>
          </developer>
          <developer>
            <id>liwensun</id>
            <name>Liwen Sun</name>
            <url>https://github.com/liwensun</url>
          </developer>
          <developer>
            <id>mukulmurthy</id>
            <name>Mukul Murthy</name>
            <url>https://github.com/mukulmurthy</url>
          </developer>
          <developer>
            <id>tdas</id>
            <name>Tathagata Das</name>
            <url>https://github.com/tdas</url>
          </developer>
          <developer>
            <id>zsxwing</id>
            <name>Shixiong Zhu</name>
            <url>https://github.com/zsxwing</url>
          </developer>
          <developer>
            <id>scottsand-db</id>
            <name>Scott Sandre</name>
            <url>https://github.com/scottsand-db</url>
          </developer>
          <developer>
            <id>windpiger</id>
            <name>Jun Song</name>
            <url>https://github.com/windpiger</url>
          </developer>
        </developers>
  )

}

