from delta.tables import DeltaTable as DeltaTable
from delta.testing.utils import PySparkTestCase as PySparkTestCase
from pyspark import SparkConf as SparkConf, SparkContext as SparkContext
from pyspark.sql import Row as Row, SQLContext as SQLContext, functions as functions
from typing import Any

class DeltaSqlTests(PySparkTestCase):
    spark: Any = ...
    temp_path: Any = ...
    temp_file: Any = ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_vacuum(self) -> None: ...
    def test_describe_history(self) -> None: ...
    def test_generate(self) -> None: ...
    def test_convert(self) -> None: ...
