from pyspark.sql.functions import *
from pyspark.sql.types import *
from delta.tables import *
from delta.testing.utils import PySparkTestCase as PySparkTestCase
from typing import Any

class DeltaTableTests(PySparkTestCase):
    sqlContext: Any = ...
    spark: Any = ...
    tempPath: Any = ...
    tempFile: Any = ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_forPath(self) -> None: ...
    def test_alias_and_toDF(self) -> None: ...
    def test_delete(self) -> None: ...
    def test_generate(self) -> None: ...
    def test_update(self) -> None: ...
    def test_merge(self) -> None: ...
    def test_history(self) -> None: ...
    def test_vacuum(self) -> None: ...
    def test_convertToDelta(self) -> None: ...
    def test_isDeltaTable(self) -> None: ...
