/*
 * Copyright (2021) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.delta.flink.table;

import dev.failsafe.function.CheckedSupplier;
import io.unitycatalog.client.ApiClient;
import io.unitycatalog.client.ApiException;
import io.unitycatalog.client.api.SchemasApi;
import io.unitycatalog.client.api.TablesApi;
import io.unitycatalog.client.api.TemporaryCredentialsApi;
import io.unitycatalog.client.model.*;
import java.net.URI;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * A {@code UnityCatalog} is a {@link DeltaCatalog} implementation that interacts with an external
 * catalog service via UnityCatalog OSS APIs.
 *
 * <p>This catalog resolves table metadata and access credentials by communicating with a remote
 * catalog endpoint. It is typically used in environments where table discovery, authorization, and
 * credential issuance are managed centrally by a service rather than through filesystem-based
 * catalogs.
 *
 * <p>The catalog uses:
 *
 * <ul>
 *   <li>a REST endpoint to load table metadata (e.g., storage location, table identifiers), and
 *   <li>temporary credentials generated by the catalog service to access underlying storage.
 * </ul>
 *
 * <p>Authentication to the catalog service is performed using a bearer token supplied at
 * construction time. The token is attached to all outgoing REST requests.
 */
public class UnityCatalog implements DeltaCatalog {

  private static Logger LOG = LoggerFactory.getLogger(UnityCatalog.class);

  private final String name;
  private final URI endpoint;
  private final String token;

  /**
   * Lazily initialized API client used to communicate with the catalog service. This field is
   * marked transient to avoid serialization issues in distributed environments.
   */
  protected transient ApiClient apiClient;

  /**
   * Creates a {@code RESTCatalog} with the given endpoint and authentication token.
   *
   * @param endpoint the catalog REST endpoint URI as a string
   * @param token a bearer token used to authenticate REST requests
   */
  public UnityCatalog(String name, String endpoint, String token) {
    this.name = name;
    this.endpoint = URI.create(endpoint);
    this.token = token;
  }

  /**
   * Returns the catalog name.
   *
   * @return the catalog name
   */
  public String getName() {
    return name;
  }

  /**
   * Returns the catalog REST endpoint.
   *
   * @return the catalog endpoint URI
   */
  public URI getEndpoint() {
    return endpoint;
  }

  /**
   * Returns the authentication token used for catalog access.
   *
   * @return the catalog bearer token
   */
  public String getToken() {
    return token;
  }

  /**
   * Lazily initialize an {@link ApiClient} for communicating with the catalog service.
   *
   * @return an initialized {@link ApiClient}
   */
  protected ApiClient getApiClient() {
    if (apiClient == null) {
      apiClient =
          new ApiClient()
              .setScheme(endpoint.getScheme())
              .setHost(endpoint.getHost())
              .setPort(endpoint.getPort())
              .setRequestInterceptor(request -> request.header("Authorization", "Bearer " + token));
    }
    return apiClient;
  }

  protected <RET> RET withRetry(CheckedSupplier<RET> body) {
    // TODO implement retry
    try {
      return body.get();
    } catch (Throwable e) {
      if (e instanceof ApiException) {
        int code = ((ApiException) e).getCode();
        if (code < 500 && code > 300) {
          throw new ExceptionUtils.ResourceNotFoundException(e.getMessage());
        }
        throw new RuntimeException(e);
      }
      throw new RuntimeException(e);
    }
  }

  /**
   * Loads table metadata from the remote catalog.
   *
   * <p>This method retrieves table information via the catalog REST API and resolves the table
   * storage location into a normalized {@link URI}. The returned {@link TableBrief} contains the
   * table UUID and resolved storage path.
   *
   * @param tableId the logical identifier of the table
   * @return a {@link TableBrief} describing the resolved table
   */
  @Override
  public TableBrief getTable(String tableId) {
    return withRetry(
        () -> {
          TablesApi tablesApi = new TablesApi(getApiClient());
          TableInfo tableInfo = tablesApi.getTable(tableId, null, null);
          TableBrief brief = new TableBrief();
          brief.tablePath =
              AbstractKernelTable.normalize(
                  URI.create(Objects.requireNonNull(tableInfo.getStorageLocation())));
          brief.uuid = tableInfo.getTableId();
          LOG.debug("Loaded table with UUID {} at {}", brief.uuid, brief.tablePath);
          return brief;
        });
  }

  /**
   * Retrieves temporary credentials required to access the underlying storage for the given table.
   *
   * <p>This implementation requests short-lived credentials from the catalog service that are
   * scoped to the specified table and operation type (read/write).
   *
   * <p>The returned configuration map contains Hadoop-compatible S3A credential keys.
   *
   * @param tableId the table identifier for which credentials are requested
   * @return a map of filesystem configuration properties containing temporary credentials
   * @throws RuntimeException if credential generation fails due to API or network errors
   */
  @Override
  public Map<String, String> getCredentials(String tableId) {
    return withRetry(
        () -> {
          TemporaryCredentialsApi credentialsApi = new TemporaryCredentialsApi(getApiClient());
          TemporaryCredentials credentials =
              credentialsApi.generateTemporaryTableCredentials(
                  new GenerateTemporaryTableCredential()
                      .tableId(tableId)
                      .operation(TableOperation.READ_WRITE));

          Map<String, String> result = new HashMap<>();

          // AWS credentials
          // TODO: Add Azure and GCP credential support
          if (credentials.getAwsTempCredentials() != null) {
            result.put("fs.s3a.access.key", credentials.getAwsTempCredentials().getAccessKeyId());
            result.put(
                "fs.s3a.secret.key", credentials.getAwsTempCredentials().getSecretAccessKey());
            result.put(
                "fs.s3a.session.token", credentials.getAwsTempCredentials().getSessionToken());
            if (credentials.getExpirationTime() != null) {
              result.put(
                  CredentialManager.CREDENTIAL_EXPIRATION_KEY,
                  credentials.getExpirationTime().toString());
            }
          }
          return result;
        });
  }

  /* ===================================
   *     Extra UnityCatalog Operations
   * ==================================*/

  public List<String> listSchemas() {
    return withRetry(
        () -> {
          SchemasApi schemasApi = new SchemasApi(getApiClient());
          return schemasApi.listSchemas(this.name, Integer.MAX_VALUE, null).getSchemas().stream()
              .map(SchemaInfo::getName)
              .collect(Collectors.toList());
        });
  }

  public SchemaInfo getSchema(String name) {
    return withRetry(
        () -> {
          SchemasApi schemasApi = new SchemasApi(getApiClient());
          return schemasApi.getSchema(String.format("%s.%s", getName(), name));
        });
  }

  public List<String> listTables(String schema) {
    return withRetry(
        () -> {
          TablesApi tablesApi = new TablesApi(getApiClient());
          return tablesApi.listTables(getName(), schema, Integer.MAX_VALUE, "").getTables().stream()
              .map(TableInfo::getName)
              .collect(Collectors.toList());
        });
  }

  public TableInfo getTableDetail(String tableId) {
    return withRetry(
        () -> {
          TablesApi tablesApi = new TablesApi(getApiClient());
          return tablesApi.getTable(tableId, false, false);
        });
  }
}
