/*
 * Copyright (2024) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.delta.sql

/**
 * An extension for Spark SQL to activate Delta SQL parser and other Delta features.
 * 
 * This class extends the shaded DeltaSparkSessionExtension from delta-spark-v1 module.
 * The shaded version is generated by the sparkShaded project.
 *
 * Example to create a SparkSession with Delta support:
 * {{{
 *    import org.apache.spark.sql.SparkSession
 *
 *    val spark = SparkSession
 *       .builder()
 *       .appName("...")
 *       .master("...")
 *       .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
 *       .getOrCreate()
 * }}}
 */
class DeltaSparkSessionExtension extends shaded.io.delta.sql.DeltaSparkSessionExtension {
  // This class inherits all functionality from the shaded DeltaSparkSessionExtension.
  // It provides a stable API in the original package namespace.
}

