/*
 * Copyright (2026) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.delta.flink.table;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import dev.failsafe.function.CheckedSupplier;
import io.delta.kernel.internal.types.DataTypeJsonSerDe;
import io.delta.kernel.types.*;
import io.delta.kernel.unitycatalog.UCTableIdentifier;
import io.delta.storage.commit.TableIdentifier;
import io.delta.storage.commit.uccommitcoordinator.UCConfigUtils;
import io.delta.storage.commit.uccommitcoordinator.UCDeltaClient;
import io.delta.storage.commit.uccommitcoordinator.UCDeltaModels;
import io.delta.storage.commit.uccommitcoordinator.UCDeltaTokenBasedRestClient;
import io.delta.storage.commit.uccommitcoordinator.exceptions.NoSuchTableException;
import io.unitycatalog.client.ApiClient;
import io.unitycatalog.client.ApiClientBuilder;
import io.unitycatalog.client.ApiException;
import io.unitycatalog.client.api.SchemasApi;
import io.unitycatalog.client.api.TablesApi;
import io.unitycatalog.client.auth.TokenProvider;
import io.unitycatalog.client.model.*;
import io.unitycatalog.client.retry.JitterDelayRetryPolicy;
import java.net.URI;
import java.util.*;
import java.util.function.Consumer;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import org.apache.flink.util.Preconditions;
import org.apache.hadoop.conf.Configuration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * A {@code UnityCatalog} is a {@link DeltaCatalog} implementation that interacts with an external
 * catalog service via UnityCatalog OSS APIs.
 *
 * <p>This catalog resolves table metadata and access credentials by communicating with a remote
 * catalog endpoint. It is typically used in environments where table discovery, authorization, and
 * credential issuance are managed centrally by a service rather than through filesystem-based
 * catalogs.
 *
 * <p>The catalog uses:
 *
 * <ul>
 *   <li>a REST endpoint to load table metadata (e.g., storage location, table identifiers), and
 *   <li>temporary credentials generated by the catalog service to access underlying storage.
 * </ul>
 *
 * <p>Authentication to the catalog service is performed using a bearer token supplied at
 * construction time. The token is attached to all outgoing REST requests.
 */
public class UnityCatalog implements DeltaCatalog {

  private static final Logger LOG = LoggerFactory.getLogger(UnityCatalog.class);

  private static ColumnTypeName columnTypeName(DataType dataType) {
    if (dataType instanceof IntegerType) {
      return ColumnTypeName.INT;
    } else if (dataType instanceof LongType) {
      return ColumnTypeName.LONG;
    } else if (dataType instanceof ShortType) {
      return ColumnTypeName.SHORT;
    } else if (dataType instanceof ByteType) {
      return ColumnTypeName.BYTE;
    } else if (dataType instanceof BooleanType) {
      return ColumnTypeName.BOOLEAN;
    } else if (dataType instanceof FloatType) {
      return ColumnTypeName.FLOAT;
    } else if (dataType instanceof DoubleType) {
      return ColumnTypeName.DOUBLE;
    } else if (dataType instanceof StringType) {
      return ColumnTypeName.STRING;
    } else if (dataType instanceof BinaryType) {
      return ColumnTypeName.BINARY;
    } else if (dataType instanceof DecimalType) {
      return ColumnTypeName.DECIMAL;
    } else if (dataType instanceof DateType) {
      return ColumnTypeName.DATE;
    } else if (dataType instanceof TimestampType) {
      return ColumnTypeName.TIMESTAMP;
    } else if (dataType instanceof TimestampNTZType) {
      return ColumnTypeName.TIMESTAMP_NTZ;
    } else if (dataType instanceof ArrayType) {
      return ColumnTypeName.ARRAY;
    } else if (dataType instanceof MapType) {
      return ColumnTypeName.MAP;
    } else if (dataType instanceof StructType) {
      return ColumnTypeName.STRUCT;
    } else {
      throw new UnsupportedOperationException("Unsupported data type: " + dataType);
    }
  }

  private static String typeText(DataType dataType) {
    if (dataType instanceof DecimalType) {
      DecimalType decimalType = (DecimalType) dataType;
      return String.format("DECIMAL(%d,%d)", decimalType.getPrecision(), decimalType.getScale());
    } else if (dataType instanceof BasePrimitiveType) {
      return dataType.toString().toUpperCase(Locale.ROOT);
    } else if (dataType instanceof ArrayType) {
      ArrayType arrayType = (ArrayType) dataType;
      return String.format("ARRAY<%s>", typeText(arrayType.getElementType()));
    } else if (dataType instanceof MapType) {
      MapType mapType = (MapType) dataType;
      return String.format(
          "MAP<%s,%s>", typeText(mapType.getKeyType()), typeText(mapType.getValueType()));
    } else if (dataType instanceof StructType) {
      StructType structType = (StructType) dataType;
      return String.format(
          "STRUCT<%s>",
          structType.fields().stream()
              .map(field -> String.format("%s:%s", field.getName(), typeText(field.getDataType())))
              .collect(Collectors.joining(",")));
    } else {
      throw new UnsupportedOperationException("Unsupported data type: " + dataType);
    }
  }

  enum AuthMode {
    token,
    oauth;
  }

  static Map<String, String> buildTokenProviderConf(
      AuthMode authMode,
      String token,
      URI oauthUri,
      String oauthClientId,
      String oauthClientSecret) {
    switch (authMode) {
      case oauth:
        return Map.of(
            "type",
            "oauth",
            "oauth.uri",
            oauthUri.toString(),
            "oauth.clientId",
            oauthClientId,
            "oauth.clientSecret",
            oauthClientSecret);
      default:
        return Map.of("type", "static", "token", token);
    }
  }

  /**
   * Builds the {@code ucConfig} map consumed by {@link UCDeltaTokenBasedRestClient}: the endpoint
   * under {@code uri}, the auth settings under the {@code auth.} prefix, and the app versions under
   * the {@code appVersions.} prefix.
   */
  static Map<String, String> buildUcConfig(
      URI endpoint,
      AuthMode authMode,
      String token,
      URI oauthUri,
      String oauthClientId,
      String oauthClientSecret) {
    Map<String, String> ucConfig = new HashMap<>();
    ucConfig.put(UCConfigUtils.URI_KEY, endpoint.toString());
    buildTokenProviderConf(authMode, token, oauthUri, oauthClientId, oauthClientSecret)
        .forEach((key, value) -> ucConfig.put(UCConfigUtils.AUTH_PREFIX + key, value));
    VersionHelper.appVersions()
        .forEach(
            (name, version) -> ucConfig.put(UCConfigUtils.APP_VERSIONS_PREFIX + name, version));
    return ucConfig;
  }

  private final String name;
  private final URI endpoint;
  private final AuthMode authMode;
  private String token;
  private URI oauthUri;
  private String oauthClientId;
  private String oauthClientSecret;
  private final boolean credentialVendingEnabled;

  /**
   * Lazily initialized API client used to communicate with the catalog service. This field is
   * marked transient to avoid serialization issues in distributed environments.
   */
  protected transient ApiClient apiClient;

  /** Client for table operations backed by the UC Delta-Tables API. */
  protected transient UCDeltaClient deltaClient;

  /**
   * Creates a {@code RESTCatalog} with the given endpoint and authentication token.
   *
   * @param name catalog name
   * @param endpoint the catalog REST endpoint URI as a string
   * @param token a bearer token used to authenticate REST requests
   */
  public UnityCatalog(String name, URI endpoint, String token) {
    this(name, endpoint, token, true);
  }

  public UnityCatalog(String name, URI endpoint, String token, boolean credentialVendingEnabled) {
    this.name = name;
    this.endpoint = endpoint;
    this.token = token;
    this.authMode = AuthMode.token;
    this.credentialVendingEnabled = credentialVendingEnabled;
  }

  /**
   * Creates a {@code RESTCatalog} with the given endpoint and OAuth authentication.
   *
   * @param name catalog name
   * @param endpoint the catalog REST endpoint URI as a string
   * @param oauthUri oauth uri
   * @param clientId oauth clientId
   * @param clientSecret oauth client secret
   */
  public UnityCatalog(
      String name, URI endpoint, URI oauthUri, String clientId, String clientSecret) {
    this(name, endpoint, oauthUri, clientId, clientSecret, true);
  }

  public UnityCatalog(
      String name,
      URI endpoint,
      URI oauthUri,
      String clientId,
      String clientSecret,
      boolean credentialVendingEnabled) {
    this.name = name;
    this.endpoint = endpoint;
    this.authMode = AuthMode.oauth;
    this.oauthUri = oauthUri;
    this.oauthClientId = clientId;
    this.oauthClientSecret = clientSecret;
    this.credentialVendingEnabled = credentialVendingEnabled;
  }

  /**
   * Returns the catalog name.
   *
   * @return the catalog name
   */
  public String getName() {
    return name;
  }

  /**
   * Returns the catalog REST endpoint.
   *
   * @return the catalog endpoint URI
   */
  public URI getEndpoint() {
    return endpoint;
  }

  /**
   * Returns the authentication token used for catalog access.
   *
   * @return the catalog bearer token
   */
  public String getToken() {
    return token;
  }

  /** @return the current ApiClient */
  public ApiClient getApiClient() {
    return apiClient;
  }

  /**
   * Parses {@code schema.table} or {@code catalog.schema.table} into a {@link UCTableIdentifier}.
   * In the 2-part form the catalog defaults to this catalog's name; in the 3-part form the leading
   * segment must equal this catalog's name.
   */
  UCTableIdentifier toUcTableIdentifier(String qualifiedTableName) {
    String[] namespaces = qualifiedTableName.split("\\.");
    Preconditions.checkArgument(namespaces.length == 2 || namespaces.length == 3);
    String catalogName;
    String schemaName;
    String tableName;
    if (namespaces.length == 3) {
      Preconditions.checkArgument(
          namespaces[0].equals(getName()),
          String.format(
              "table's catalog name %s must match catalog's name %s", namespaces[0], getName()));
      catalogName = namespaces[0];
      schemaName = namespaces[1];
      tableName = namespaces[2];
    } else {
      catalogName = getName();
      schemaName = namespaces[0];
      tableName = namespaces[1];
    }
    return new UCTableIdentifier(catalogName, schemaName, tableName);
  }

  @Override
  public void open() {
    if (apiClient == null) {
      Map<String, String> tokenProviderConf =
          buildTokenProviderConf(authMode, token, oauthUri, oauthClientId, oauthClientSecret);
      ApiClientBuilder builder =
          ApiClientBuilder.create()
              .uri(endpoint)
              .tokenProvider(TokenProvider.create(tokenProviderConf))
              .retryPolicy(JitterDelayRetryPolicy.builder().maxAttempts(5).build());
      Map<String, String> appVersions = VersionHelper.appVersions();
      appVersions.forEach(builder::addAppVersion);
      apiClient = builder.build();
    }
    if (deltaClient == null) {
      Map<String, String> ucConfig =
          buildUcConfig(endpoint, authMode, token, oauthUri, oauthClientId, oauthClientSecret);
      ucConfig.put(
          UCConfigUtils.CREDENTIAL_VENDING_ENABLED_KEY, Boolean.toString(credentialVendingEnabled));
      deltaClient =
          new UCDeltaTokenBasedRestClient(ucConfig, /* hadoopConfSupplier = */ Configuration::new);
    }
  }

  protected <RET> RET withErrorHandling(CheckedSupplier<RET> body) {
    // TODO implement retry
    try {
      return body.get();
    } catch (Throwable e) {
      if (e instanceof ApiException) {
        ApiException apiException = (ApiException) e;
        try {
          JsonNode node = new ObjectMapper().readTree(apiException.getResponseBody());
          switch (node.get("error_code").asText()) {
            case "TABLE_ALREADY_EXISTS":
              throw new ExceptionUtils.ResourceAlreadyExistException(node.get("message").asText());
            case "TABLE_DOES_NOT_EXIST":
              throw new ExceptionUtils.ResourceNotFoundException(node.get("message").asText());
            default:
              throw new RuntimeException(apiException);
          }
        } catch (Exception ex) {
          throw ExceptionUtils.wrap(ex);
        }
      }
      throw ExceptionUtils.wrap(e);
    }
  }

  /** Converts a {@code schema.table} or {@code catalog.schema.table} name to the storage id. */
  private TableIdentifier toStorageTableIdentifier(String qualifiedTableName) {
    UCTableIdentifier id = toUcTableIdentifier(qualifiedTableName);
    return new TableIdentifier(
        new String[] {id.getCatalogName(), id.getSchemaName()}, id.getTableName());
  }

  /**
   * Loads table metadata from the remote catalog.
   *
   * <p>This method retrieves table information via the catalog REST API and resolves the table
   * storage location into a normalized {@link URI}. The returned {@link TableDescriptor} contains
   * the table UUID and resolved storage path.
   *
   * @param tableName the logical identifier of the table
   * @return a {@link TableDescriptor} describing the resolved table
   */
  @Override
  public TableDescriptor getTable(String tableName) {
    Objects.requireNonNull(tableName);
    return withErrorHandling(
        () -> {
          UCDeltaModels.TableInfo tableInfo;
          try {
            tableInfo = deltaClient.loadTable(toStorageTableIdentifier(tableName));
          } catch (NoSuchTableException e) {
            throw new ExceptionUtils.ResourceNotFoundException(e.getMessage());
          }
          TableDescriptor brief =
              new TableDescriptor(
                  tableName,
                  tableInfo.getTableId().toString(),
                  AbstractKernelTable.normalize(
                      URI.create(Objects.requireNonNull(tableInfo.getLocation()))),
                  tableInfo.getStorageProperties());
          LOG.debug("Loaded table with UUID {} at {}", brief.uuid, brief.tablePath);
          return brief;
        });
  }

  /**
   * Creates a new table in the backed UnityCatalog
   *
   * <p>The {@code tableId} identifies the table within UC. This operation registers the table
   * metadata with the remote catalog, including schema, partition specification, and table
   * properties.
   *
   * <p>This call will create a staging table, init the snapshot, then upgrade the staging table to
   * real table.
   */
  @Override
  public void createTable(
      String tableId,
      StructType schema,
      List<String> partitions,
      Map<String, String> properties,
      Consumer<TableDescriptor> callback) {
    Objects.requireNonNull(tableId);
    Objects.requireNonNull(schema);
    Objects.requireNonNull(partitions);
    Objects.requireNonNull(properties);
    withErrorHandling(
        () -> {
          TablesApi tablesApi = new TablesApi(apiClient);
          // Obtain names
          UCTableIdentifier tableIdentifier = toUcTableIdentifier(tableId);
          String schemaName = tableIdentifier.getSchemaName();
          String tableName = tableIdentifier.getTableName();
          // Column Info
          List<ColumnInfo> columnInfos =
              IntStream.range(0, schema.fields().size())
                  .mapToObj(
                      index -> {
                        StructField field = schema.fields().get(index);
                        ColumnInfo colInfo =
                            new ColumnInfo()
                                .name(field.getName())
                                .typeName(columnTypeName(field.getDataType()))
                                .typeText(typeText(field.getDataType()))
                                .typeJson(DataTypeJsonSerDe.serializeDataType(field.getDataType()))
                                .position(index)
                                .nullable(field.isNullable());
                        if (field.getDataType() instanceof DecimalType) {
                          DecimalType decimalType = (DecimalType) field.getDataType();
                          colInfo
                              .typePrecision(decimalType.getPrecision())
                              .typeScale(decimalType.getScale());
                        }
                        return colInfo;
                      })
                  .collect(Collectors.toList());

          // Create a staging table and init the storage
          StagingTableInfo stagingTableInfo =
              tablesApi.createStagingTable(
                  new CreateStagingTable()
                      .catalogName(getName())
                      .schemaName(schemaName)
                      .name(tableName));

          // Init Delta snapshot
          String storageLocation = stagingTableInfo.getStagingLocation();
          Objects.requireNonNull(storageLocation);

          TableDescriptor desc =
              new TableDescriptor(tableId, stagingTableInfo.getId(), URI.create(storageLocation));
          callback.accept(desc);

          tablesApi.createTable(
              new CreateTable()
                  .catalogName(getName())
                  .schemaName(schemaName)
                  .name(tableName)
                  .storageLocation(stagingTableInfo.getStagingLocation())
                  .tableType(TableType.MANAGED)
                  .dataSourceFormat(DataSourceFormat.DELTA)
                  .columns(columnInfos)
                  .properties(properties));
          return null;
        });
  }

  /**
   * Retrieves temporary credentials required to access the underlying storage for the given table.
   *
   * <p>This implementation requests short-lived credentials from the catalog service that are
   * scoped to the specified table and operation type (read/write).
   *
   * <p>The returned Hadoop configuration uses the renewable credential providers supplied by {@code
   * unitycatalog-hadoop}.
   *
   * <p>These providers use filesystem-specific expiration settings, so {@link CredentialManager}
   * does not schedule another refresh for UC credentials. Credential renewal is handled by {@code
   * unitycatalog-hadoop}; {@code renewCredential.enabled} defaults to {@code true}.
   *
   * @param tableName the three-part table name for which credentials are requested
   * @return a map of filesystem configuration properties containing temporary credentials
   * @throws RuntimeException if credential generation fails due to API or network errors
   */
  @Override
  public Map<String, String> getCredentials(String tableName) {
    Objects.requireNonNull(tableName);
    return withErrorHandling(
        () -> deltaClient.loadTable(toStorageTableIdentifier(tableName)).getStorageProperties());
  }

  /* ===================================
   *     Extra UnityCatalog Operations
   * ==================================*/

  public List<String> listSchemas() {
    return withErrorHandling(
        () -> {
          SchemasApi schemasApi = new SchemasApi(apiClient);
          return schemasApi.listSchemas(this.name, Integer.MAX_VALUE, null).getSchemas().stream()
              .map(SchemaInfo::getName)
              .collect(Collectors.toList());
        });
  }

  public SchemaInfo getSchema(String name) {
    return withErrorHandling(
        () -> {
          SchemasApi schemasApi = new SchemasApi(apiClient);
          return schemasApi.getSchema(String.format("%s.%s", getName(), name));
        });
  }

  public List<String> listTables(String schema) {
    return withErrorHandling(
        () -> {
          TablesApi tablesApi = new TablesApi(apiClient);
          return tablesApi.listTables(getName(), schema, Integer.MAX_VALUE, "").getTables().stream()
              .map(TableInfo::getName)
              .collect(Collectors.toList());
        });
  }

  public TableInfo getTableDetail(String tableId) {
    return withErrorHandling(
        () -> {
          TablesApi tablesApi = new TablesApi(apiClient);
          return tablesApi.getTable(tableId, false, false);
        });
  }
}
