/*
 * Copyright (2026) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.apache.spark.sql.delta

import java.util.Locale

import scala.collection.JavaConverters._
import scala.concurrent.duration.DurationInt

import com.databricks.spark.util.{Log4jUsageLogger, MetricDefinitions}
import org.apache.spark.sql.delta.actions.{Protocol, TableFeatureProtocolUtils}
import org.apache.spark.sql.delta.concurrency.{PhaseLockingTestMixin, TransactionExecutionTestMixin}
import org.apache.spark.sql.delta.sources.DeltaSQLConf
import org.apache.spark.sql.delta.util.JsonUtils
import org.apache.spark.sql.delta.cic.DropSequenceRequest
import org.mockito.ArgumentMatchers.{any, anyBoolean}
import org.mockito.Mockito.{doAnswer, spy}

import org.apache.spark.sql.catalyst.TableIdentifier
import org.apache.spark.sql.connector.catalog.Identifier
import org.apache.spark.sql.execution.datasources.v2.V2SessionCatalog
import org.apache.spark.util.ThreadUtils

/**
 * Verifies the table-level CIC conversion and downgrade DDL on the service backend:
 *
 *   - SYNC IDENTITY reconciles / repairs an existing service sequence.
 *   - CIC feature opt-in (ALTER ... SET TBLPROPERTIES) converts a stock identity table.
 *   - DROP FEATURE returns a service-backed table to stock identity.
 *   - The `identityColumn.concurrent.enabled` kill switch blocks conversion / repair while
 *     leaving the DROP FEATURE escape hatch working.
 *
 * Re-uses the suite scaffolding from [[ConcurrentIdentityColumnSuiteBase]] (table
 * properties enabling the CIC feature, MERGE helpers) and the same
 * [[SharedLocalIdentitySequenceService]] backend injection documented on
 * [[ConcurrentIdentityColumnServiceBackendSuite]].
 *
 * The phase-locking mixins ([[TransactionExecutionTestMixin]], [[PhaseLockingTestMixin]]) back the
 * two SYNC-vs-write race tests, which hold a transaction at pre-commit while a conflicting one
 * commits. Note that the tests still run sequentially.
 */
class ConcurrentIdentityColumnConversionSuite extends ConcurrentIdentityColumnSuiteBase
  with TransactionExecutionTestMixin
  with PhaseLockingTestMixin {

  import testImplicits._

  private def selectMaxId: Long =
    spark.sql(s"SELECT max(ids) AS m FROM delta.`$tempPath`").head().getLong(0)

  private def syncedSequenceId: Option[String] =
    ConcurrentIdentityColumnSchema.getSequenceId(deltaLog.update().metadata.schema("ids"))

  /**
   * Fabricates an unconverted LEGACY table: a plain identity table whose protocol carries
   * the CIC feature but whose columns have no sequence pointer, optionally with rows
   * written through the stock identity path. This is unconverted on-disk shape; it can no
   * longer be produced through DDL (CREATE stamps on feature opt-in and ALTER converts), so
   * the protocol upgrade is committed raw, deliberately bypassing the conversion hook.
   */
  private def createLegacyTableWithCicWithoutSequenceId(rows: Seq[Int] = Nil): Unit = {
    spark.sql(
      s"""CREATE TABLE target (
         |  ids BIGINT GENERATED ALWAYS AS IDENTITY,
         |  values INT)
         |USING DELTA
         |LOCATION '$tempPath'
         |tblproperties(
         |  ${TableFeatureProtocolUtils.propertyKey(IdentityColumnsTableFeature)} = 'enabled')
         |""".stripMargin)
    if (rows.nonEmpty) {
      // Stock identity writes (the CIC feature is not on the protocol yet).
      spark.sql(
        s"INSERT INTO delta.`$tempPath` (values) VALUES ${rows.map(v => s"($v)").mkString(", ")}")
    }
    val txn = deltaLog.startTransaction()
    txn.updateProtocol(txn.protocol.merge(
      Protocol.forTableFeature(ConcurrentIdentityColumnsTableFeature)))
    txn.commit(Nil, DeltaOperations.ManualUpdate)
    assert(deltaLog.update().protocol.isFeatureSupported(ConcurrentIdentityColumnsTableFeature),
      "Legacy fixture: the raw protocol upgrade must land the CIC feature.")
    assert(syncedSequenceId.isEmpty,
      "Legacy fixture: the raw upgrade must NOT stamp a sequence pointer.")
  }

  test("SYNC IDENTITY reconciles the service sequence and mints a fresh id (service backend)") {
    // GENERATED BY DEFAULT lets us insert explicit values the service never saw. After SYNC the
    // service must be reseeded past them (minting a NEW sequence id) so the next auto value clears
    // the explicit max instead of colliding from the original start.
    withTable("target") {
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(createTargetTableStatement(Seq(
          "ids BIGINT GENERATED BY DEFAULT AS IDENTITY",
          "values INT")))
        spark.sql(s"INSERT INTO delta.`$tempPath` (ids, values) VALUES (100, 1), (200, 2)")

        val seqBefore = syncedSequenceId.get
        val numCreatesBefore = localService.createSequenceCount
        val serviceTableId =
          ConcurrentIdentityColumnSchema.sequenceServiceTableId(deltaLog.update().metadata)
        val dropsBefore = localService.dropSequenceCount
        spark.sql(s"ALTER TABLE delta.`$tempPath` ALTER COLUMN ids SYNC IDENTITY")

        assert(syncedSequenceId.get != seqBefore, "SYNC must mint a fresh sequence id.")
        assert(localService.createSequenceCount === numCreatesBefore + 1,
          "SYNC must create exactly one new sequence.")
        assert(localService.dropSequenceCount === dropsBefore + 1,
          "SYNC must retire the superseded sequence (one dropSequence call).")
        assert(!localService.hasSequence(serviceTableId, seqBefore),
          "SYNC must drop the old sequence rather than orphan it.")

        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (3)")
        val autoId = readDeltaTable(tempPath).where("values = 3").select("ids").head().getLong(0)
        assert(autoId > 200L, s"Post-SYNC auto value must clear the explicit max 200, got $autoId.")
        assertCorrectIdentityColumn(readDeltaTable(tempPath).select("ids"), expectedSize = 3L)
      }
    }
  }

  test("SYNC IDENTITY reconciles a descending (negative-step) sequence past the data min") {
    // Negative-step counterpart of the SYNC test: for a descending column SYNC must scan the
    // data MIN (not max) and reseed the service strictly below it, so the next auto value clears
    // the explicit min instead of colliding from the original start.
    withTable("target") {
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(createTargetTableStatement(Seq(
          "ids BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 INCREMENT BY -1)",
          "values INT")))
        spark.sql(s"INSERT INTO delta.`$tempPath` (ids, values) VALUES (-100, 1), (-200, 2)")

        val seqBefore = syncedSequenceId.get
        val numCreatesBefore = localService.createSequenceCount
        val serviceTableId =
          ConcurrentIdentityColumnSchema.sequenceServiceTableId(deltaLog.update().metadata)
        val dropsBefore = localService.dropSequenceCount
        spark.sql(s"ALTER TABLE delta.`$tempPath` ALTER COLUMN ids SYNC IDENTITY")

        assert(syncedSequenceId.get != seqBefore, "SYNC must mint a fresh sequence id.")
        assert(localService.createSequenceCount === numCreatesBefore + 1,
          "SYNC must create exactly one new sequence.")
        assert(localService.dropSequenceCount === dropsBefore + 1,
          "SYNC must retire the superseded sequence (one dropSequence call).")
        assert(!localService.hasSequence(serviceTableId, seqBefore),
          "SYNC must drop the old sequence rather than orphan it.")

        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (3)")
        val autoId = readDeltaTable(tempPath).where("values = 3").select("ids").head().getLong(0)
        assert(autoId < -200L,
          s"Post-SYNC auto value must clear the explicit min -200, got $autoId.")
        assertCorrectIdentityColumn(readDeltaTable(tempPath).select("ids"), expectedSize = 3L)
      }
    }
  }

  test("DROP COLUMN of an identity column retires its service sequence") {
    withTable("target") {
      withSQLConf(
        DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true",
        DeltaSQLConf.DELTA_ALTER_TABLE_DROP_COLUMN_ENABLED.key -> "true") {
        spark.sql(createTargetTableStatement(Seq(
          "ids BIGINT GENERATED ALWAYS AS IDENTITY",
          "values INT")))
        // DROP COLUMN requires column mapping.
        spark.sql(
          s"ALTER TABLE delta.`$tempPath` SET TBLPROPERTIES ('delta.columnMapping.mode' = 'name')")
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (1), (2)")

        val droppedSeq = syncedSequenceId.getOrElse(
          fail("Setup: the CIC table must stamp a sequence on the identity column."))
        val serviceTableId =
          ConcurrentIdentityColumnSchema.sequenceServiceTableId(deltaLog.update().metadata)
        assert(localService.hasSequence(serviceTableId, droppedSeq),
          "Setup: the service sequence must exist before DROP COLUMN.")
        val dropsBefore = localService.dropSequenceCount

        spark.sql(s"ALTER TABLE delta.`$tempPath` DROP COLUMN ids")

        assert(localService.dropSequenceCount === dropsBefore + 1,
          "DROP COLUMN of an identity column must retire its service sequence.")
        assert(!localService.hasSequence(serviceTableId, droppedSeq),
          "DROP COLUMN must drop the sequence rather than orphan it.")
      }
    }
  }

  test("SYNC IDENTITY refuses an unconverted legacy table") {
    // SYNC is repair-only: it reseeds an EXISTING service sequence. A legacy table (CIC
    // feature on, no sequence pointer) is unconverted state, and converting is the conversion
    // DDL's concern, not SYNC's. SYNC must refuse with the missing-stamp error and leave the
    // state untouched.
    withTable("target") {
      createLegacyTableWithCicWithoutSequenceId(rows = Seq(10, 20, 30))
      val numCreatesBefore = localService.createSequenceCount

      val cause = cicReservationCause(intercept[Exception] {
        spark.sql(s"ALTER TABLE delta.`$tempPath` ALTER COLUMN ids SYNC IDENTITY")
      })
      checkError(
        cause,
        condition = "DELTA_CONCURRENT_IDENTITY_COLUMN_CONVERSION_INCOMPLETE",
        sqlState = "XXKDS",
        parameters = cause.getMessageParameters.asScala.toMap)
      assert(localService.createSequenceCount === numCreatesBefore,
        "A refused SYNC must not create a sequence.")
      assert(syncedSequenceId.isEmpty, "A refused SYNC must not stamp a sequenceId.")
    }
  }

  test("SYNC IDENTITY repairs independently of the session conf") {
    // SYNC no longer routes on CONCURRENT_IDENTITY_COLUMN_ENABLED: on a stamped table it is
    // always the service repair (the old conf-off downgrade flow is gone; leaving the service
    // backend is table-level DDL). Run SYNC with the conf at its default (off) and verify it
    // still re-mints a fresh sequence and keeps the stamp.
    withTable("target") {
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(createTargetTableStatement(Seq(
          "ids BIGINT GENERATED ALWAYS AS IDENTITY",
          "values INT")))
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (10), (20), (30)")
      }
      assert(syncedSequenceId.isDefined, "Setup: a conf-on table must carry a sequenceId.")
      val seqBefore = syncedSequenceId.get
      val numCreatesBefore = localService.createSequenceCount

      // Conf at its default (off): SYNC must still repair, not downgrade.
      spark.sql(s"ALTER TABLE delta.`$tempPath` ALTER COLUMN ids SYNC IDENTITY")

      assert(syncedSequenceId.isDefined, "Repair must keep the column service-backed.")
      assert(syncedSequenceId.get != seqBefore, "Repair must mint a fresh sequence id.")
      assert(localService.createSequenceCount === numCreatesBefore + 1,
        "Repair must create exactly one new sequence.")

      // The fresh sequence must be reseeded PAST the data: a write after SYNC must generate ids
      // beyond the existing max, proving the effective high-water mark advanced.
      val maxBefore = selectMaxId
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (40)")
      }
      assert(selectMaxId > maxBefore,
        s"Post-SYNC values must clear the pre-SYNC max $maxBefore, got $selectMaxId.")
    }
  }

  test("a service-backed write that commits after a racing SYNC IDENTITY is rejected") {
    // The central safety property of CIC SYNC: it re-stamps the sequence pointer
    // (delta.identity.concurrent.sequenceId) as a GENERIC
    // metadata change (deliberately NOT setSyncIdentity), so a concurrent write that reserved from
    // the old sequence before SYNC committed must be rejected on commit, not allowed to emit values
    // that could collide with the freshly minted sequence. Deterministic via the phase-locking
    // transaction observer: the write is held at pre-commit while SYNC commits.
    withTable("target") {
      spark.sql(createTargetTableStatement(Seq(
        "ids BIGINT GENERATED ALWAYS AS IDENTITY",
        "values INT")))
      spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (1), (2), (3)")

      val pool = ThreadUtils.newDaemonSingleThreadExecutor("cic-write-vs-sync")
      try {
        val (writeObserver, writeFuture) = runQueryWithObserver(
          name = "write",
          pool,
          s"INSERT INTO delta.`$tempPath` (values) VALUES (10), (20)")
        unblockUntilPreCommit(writeObserver)
        busyWaitFor(writeObserver.phases.preparePhase.hasEntered, timeout)

        // SYNC commits first, minting a new sequence and re-stamping the pointer.
        spark.sql(s"ALTER TABLE delta.`$tempPath` ALTER COLUMN ids SYNC IDENTITY")

        unblockCommit(writeObserver)
        val ex = intercept[Exception] {
          ThreadUtils.awaitResult(writeFuture, 30.seconds)
        }
        assert(causeChain(ex).exists(_.isInstanceOf[java.util.ConcurrentModificationException]),
          s"The racing write must fail with a Delta commit conflict; got: $ex")
      } finally {
        pool.shutdownNow()
      }

      // Interleaving-independent invariant: no duplicate identity values. The rejected write
      // committed nothing, so only the seeded rows remain.
      val ids = readDeltaTable(tempPath).select("ids")
      assert(ids.count() === ids.distinct().count(),
        "A SYNC/write race must never produce duplicate identity values.")
    }
  }

  test("a SYNC IDENTITY that commits after a racing CIC write is rejected") {
    // The other ordering: SYNC calls readWholeTable, so a write that appends rows while SYNC is in
    // flight must abort SYNC (the user re-runs it and re-scans the new data). Deterministic: SYNC
    // is held at pre-commit while the write commits.
    withTable("target") {
      spark.sql(createTargetTableStatement(Seq(
        "ids BIGINT GENERATED ALWAYS AS IDENTITY",
        "values INT")))
      spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (1), (2), (3)")

      val pool = ThreadUtils.newDaemonSingleThreadExecutor("cic-sync-vs-write")
      try {
        val (syncObserver, syncFuture) = runQueryWithObserver(
          name = "sync",
          pool,
          s"ALTER TABLE delta.`$tempPath` ALTER COLUMN ids SYNC IDENTITY")
        unblockUntilPreCommit(syncObserver)
        busyWaitFor(syncObserver.phases.preparePhase.hasEntered, timeout)

        // A concurrent write commits underneath the in-flight SYNC.
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (10), (20)")

        unblockCommit(syncObserver)
        val ex = intercept[Exception] {
          ThreadUtils.awaitResult(syncFuture, 30.seconds)
        }
        assert(causeChain(ex).exists(_.isInstanceOf[java.util.ConcurrentModificationException]),
          s"SYNC must abort when a write commits underneath it; got: $ex")
      } finally {
        pool.shutdownNow()
      }

      val ids = readDeltaTable(tempPath).select("ids")
      assert(ids.count() === ids.distinct().count(),
        "A SYNC/write race must never produce duplicate identity values.")
    }
  }

  private def cicFeatureOptInDdl: String =
    s"ALTER TABLE delta.`$tempPath` SET TBLPROPERTIES " +
      s"('${TableFeatureProtocolUtils.propertyKey(ConcurrentIdentityColumnsTableFeature)}' = " +
      "'supported')"

  test("CIC feature opt-in converts a plain identity table to the service backend") {
    // Conversion is table-level DDL: opting a stock identity table into the CIC feature via
    // ALTER ... SET TBLPROPERTIES mints a sequence per identity column, seeded strictly past
    // the existing data / schema HWM, and stamps the pointer. A subsequent service-backed
    // INSERT continues past the pre-conversion values.
    withTable("target") {
      spark.sql(
        s"""CREATE TABLE target (
           |  ids BIGINT GENERATED ALWAYS AS IDENTITY,
           |  values INT)
           |USING DELTA
           |LOCATION '$tempPath'
           |tblproperties(
           |  ${TableFeatureProtocolUtils.propertyKey(IdentityColumnsTableFeature)} = 'enabled')
           |""".stripMargin)
      // Stock identity writes (no CIC feature, conf off): schema-HWM generation.
      spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (10), (20), (30)")
      val maxBefore = selectMaxId
      assert(syncedSequenceId.isEmpty, "Setup: a stock identity table carries no sequenceId.")

      val numCreatesBefore = localService.createSequenceCount
      spark.sql(cicFeatureOptInDdl)

      assert(localService.createSequenceCount === numCreatesBefore + 1,
        "Conversion must mint exactly one sequence for one identity column.")
      assert(syncedSequenceId.isDefined, "Conversion must stamp the sequence pointer.")
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (40), (50)")
      }
      assert(selectMaxId > maxBefore,
        s"Post-conversion values must clear the pre-conversion max $maxBefore, got $selectMaxId.")
      assertCorrectIdentityColumn(readDeltaTable(tempPath).select("ids"), expectedSize = 5L)
    }
  }

  test("CIC feature opt-in converts an unconverted feature-on table in place") {
    // A legacy table already supports the feature but never got stamped. Re-running the
    // feature opt-in converts it in place: stamps a sequence seeded past the existing data so
    // subsequent service-backed writes continue past the pre-conversion values.
    withTable("target") {
      createLegacyTableWithCicWithoutSequenceId(rows = Seq(10, 20, 30))
      val maxBefore = selectMaxId

      spark.sql(cicFeatureOptInDdl)

      assert(syncedSequenceId.isDefined, "Conversion must stamp the sequence pointer.")
      spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (40), (50)")
      assert(selectMaxId > maxBefore,
        s"Post-conversion values must clear the pre-conversion max $maxBefore, got $selectMaxId.")
      assertCorrectIdentityColumn(readDeltaTable(tempPath).select("ids"), expectedSize = 5L)
    }
  }

  test("CIC feature opt-in is idempotent on an already-converted table") {
    // Re-running the property set on a stamped table must be a plain no-op property set:
    // no new sequence, same pointer.
    withTable("target") {
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(createTargetTableStatement(Seq(
          "ids BIGINT GENERATED ALWAYS AS IDENTITY",
          "values INT")))
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (10), (20)")
      }
      val seqBefore = syncedSequenceId.get
      val numCreatesBefore = localService.createSequenceCount

      spark.sql(cicFeatureOptInDdl)

      assert(localService.createSequenceCount === numCreatesBefore,
        "Re-running the opt-in on a converted table must not mint a sequence.")
      assert(syncedSequenceId.get === seqBefore,
        "Re-running the opt-in must keep the existing sequence pointer.")
    }
  }

  private def cicDropFeatureDdl: String =
    s"ALTER TABLE delta.`$tempPath` DROP FEATURE " +
      s"`${ConcurrentIdentityColumnsTableFeature.name}`"

  test("DROP FEATURE returns a service-backed table to stock identity") {
    // Leaving the service backend is table-level DDL: the pre-downgrade hook computes the
    // stock schema high-water mark from the data, strips the sequence pointer, and the
    // command drops the feature. A subsequent stock-identity INSERT continues past the
    // service-written data instead of restarting from `start`.
    withTable("target") {
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(createTargetTableStatement(Seq(
          "ids BIGINT GENERATED ALWAYS AS IDENTITY",
          "values INT")))
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (10), (20), (30)")
      }
      assert(syncedSequenceId.isDefined, "Setup: a conf-on table must carry a sequenceId.")
      val droppedSequenceId = syncedSequenceId.get
      val serviceTableId =
        ConcurrentIdentityColumnSchema.sequenceServiceTableId(deltaLog.update().metadata)
      assert(localService.hasSequence(serviceTableId, droppedSequenceId),
        "Setup: the service sequence must exist before DROP FEATURE.")
      val dropsBefore = localService.dropSequenceCount
      val maxBefore = selectMaxId

      spark.sql(cicDropFeatureDdl)

      val snapshot = deltaLog.update()
      assert(!snapshot.protocol.isFeatureSupported(ConcurrentIdentityColumnsTableFeature),
        "DROP FEATURE must remove the CIC feature from the protocol.")
      assert(syncedSequenceId.isEmpty,
        "The pre-downgrade must strip the sequence pointer.")
      assert(localService.dropSequenceCount === dropsBefore + 1,
        "DROP FEATURE must retire the service sequence (one dropSequence call).")
      assert(!localService.hasSequence(serviceTableId, droppedSequenceId),
        "DROP FEATURE must drop the service sequence rather than orphan it.")

      // Stock identity (no CIC feature, conf off) reads the schema HWM the downgrade wrote.
      spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (40), (50)")
      assert(selectMaxId > maxBefore,
        s"Post-downgrade stock values must continue past $maxBefore, got $selectMaxId.")
      assertCorrectIdentityColumn(readDeltaTable(tempPath).select("ids"), expectedSize = 5L)
    }
  }

  test("DROP FEATURE on an unconverted feature-on table returns it to stock identity") {
    // A legacy table (feature on, never stamped) can leave directly: the pre-downgrade syncs
    // its columns' schema HWMs from the data (it has no pointer to strip), so stock identity
    // continues past the already-written data.
    withTable("target") {
      createLegacyTableWithCicWithoutSequenceId(rows = Seq(10, 20, 30))
      val maxBefore = selectMaxId

      spark.sql(cicDropFeatureDdl)

      val snapshot = deltaLog.update()
      assert(!snapshot.protocol.isFeatureSupported(ConcurrentIdentityColumnsTableFeature),
        "DROP FEATURE must remove the CIC feature from the protocol.")

      spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (40), (50)")
      assert(selectMaxId > maxBefore,
        s"Post-downgrade stock values must continue past $maxBefore, got $selectMaxId.")
      assertCorrectIdentityColumn(readDeltaTable(tempPath).select("ids"), expectedSize = 5L)
    }
  }

  test("DROP FEATURE then re-convert round-trips a table with multiple CIC columns") {
    // Coverage for the multi-column + re-conversion gap: the conversion/downgrade tests elsewhere
    // are single-column and never chained. Drive a TWO-identity-column table CIC -> v1 (DROP
    // FEATURE) -> CIC (re-opt-in), asserting both columns are stamped, stripped, and re-stamped
    // together (whole-table) and that each column's values keep advancing across every transition.
    def pointer(col: String): Option[String] =
      ConcurrentIdentityColumnSchema.getSequenceId(deltaLog.update().metadata.schema(col))
    def maxOf(col: String): Long =
      spark.sql(s"SELECT max($col) AS m FROM delta.`$tempPath`").head().getLong(0)

    withTable("target") {
      // 1. CIC table with two identity columns: CREATE under the feature stamps both.
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(createTargetTableStatement(Seq(
          "idA BIGINT GENERATED ALWAYS AS IDENTITY",
          "idB BIGINT GENERATED ALWAYS AS IDENTITY",
          "values INT")))
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (10), (20), (30)")
      }
      assert(pointer("idA").isDefined && pointer("idB").isDefined,
        "CREATE under the CIC feature must stamp every identity column.")
      val (aCic, bCic) = (maxOf("idA"), maxOf("idB"))

      // 2. DROP FEATURE -> v1: strip every pointer, drop the feature, write each column's HWM.
      spark.sql(cicDropFeatureDdl)
      val snap = deltaLog.update()
      assert(!snap.protocol.isFeatureSupported(ConcurrentIdentityColumnsTableFeature),
        "DROP FEATURE must remove the CIC feature.")
      assert(pointer("idA").isEmpty && pointer("idB").isEmpty,
        "DROP FEATURE must strip the pointer from every identity column.")
      spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (40), (50)")
      assert(maxOf("idA") > aCic && maxOf("idB") > bCic,
        "Post-downgrade stock values must continue past the CIC max for both columns.")
      val (aV1, bV1) = (maxOf("idA"), maxOf("idB"))

      // 3. Re-opt-in -> CIC again: a fresh sequence per column, seeded past the v1 data.
      val createsBefore = localService.createSequenceCount
      spark.sql(cicFeatureOptInDdl)
      assert(localService.createSequenceCount === createsBefore + 2,
        "Re-conversion must mint one fresh sequence for each of the two identity columns.")
      assert(pointer("idA").isDefined && pointer("idB").isDefined,
        "Re-conversion must re-stamp every identity column.")
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (60), (70)")
      }
      assert(maxOf("idA") > aV1 && maxOf("idB") > bV1,
        "Post-re-conversion service values must continue past the v1 max for both columns.")

      // Every value of each identity column is distinct across the full round-trip.
      assertCorrectIdentityColumn(readDeltaTable(tempPath).select("idA"), expectedSize = 7L)
      assertCorrectIdentityColumn(readDeltaTable(tempPath).select("idB"), expectedSize = 7L)
    }
  }

  test("DROP FEATURE migrates the service high-water mark, not the table max/min") {
    // The local HWM should be converted to a sequence HWM and vice versa. Extreme values should
    // be ignored during this conversion. Only SYNC should take them into account.
    // For this reason this test uses GENERATED BY DEFAULT and populates which lets us insert an
    // explicit id far ABOVE the HWM. The HWM must stay BELOW the explicit data max for the two
    // migration sources to be distinguishable.

    val step = 2L
    val start = 1L
    // Force a single large reserve so the service HWM is deterministic. The 3-row insert draws
    // fewer than `reserveSize` values, so the buffer never drains: exactly one UC reserve of
    // `reserveSize` fires (no adaptive doubling, no prefetch), leaving the service's next value at
    // `start + reserveSize * step`.
    val reserveSize = 64L
    // The service HWM the downgrade must migrate: the next value the service would have minted,
    // strictly past every service-minted id and far below the explicit data max.
    val serviceHwm = start + reserveSize * step
    // The explicit id sits a full reserve-window (`reserveSize * 1024`) above the seeded range, so
    // it can never accidentally collide with a service-reserved value.
    val explicitId = serviceHwm * 1024L
    // Stock v1 continues at base = HWM + step; this also becomes the new schema HWM.
    val v1Value = serviceHwm + step
    // Re-conversion seeds the fresh sequence from schema HWM + step; this is the next service id.
    val reconvertedValue = v1Value + step
    withTable("target") {
      withSQLConf(
          DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true",
          DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_RESERVE_DRIVER_INITIAL_SIZE.key ->
            reserveSize.toString) {
        spark.sql(createTargetTableStatement(Seq(
          s"ids BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH $start INCREMENT BY $step)",
          "values INT")))
        // Service-minted rows: advance the service HWM to `serviceHwm` (a small value).
        val reservesBeforeInsert = localService.reserveIdsCount
        val reserveSizesBeforeInsert = localService.reserveRequestSizes.size
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (1), (2), (3)")
        // The large reserveSize guarantees exactly one UC reserve.
        assert(localService.reserveIdsCount === reservesBeforeInsert + 1L,
          s"Setup: the insert must trigger exactly one service reserve; got " +
            s"${localService.reserveIdsCount - reservesBeforeInsert}.")
        assert(localService.reserveRequestSizes.drop(reserveSizesBeforeInsert) === Seq(reserveSize),
          s"Setup: the single reserve must request exactly reserveSize=$reserveSize values, got " +
            s"${localService.reserveRequestSizes.drop(reserveSizesBeforeInsert)}.")
        // Explicit id far above the HWM (BY DEFAULT permits it). Touches no service, feeds no HWM.
        spark.sql(s"INSERT INTO delta.`$tempPath` (ids, values) VALUES ($explicitId, 99)")
      }
      assert(syncedSequenceId.isDefined, "Setup: a conf-on table must carry a sequenceId.")
      assert(selectMaxId === explicitId,
        s"Setup: the explicit id $explicitId must be the table max, got $selectMaxId.")
      assert(selectMaxId > serviceHwm,
        s"Setup: the table max $selectMaxId must sit far above the service HWM $serviceHwm so " +
          "the two migration sources are distinguishable.")

      // 1. DROP FEATURE -> v1: the downgrade migrates the SERVICE HWM, not the data max.
      spark.sql(cicDropFeatureDdl)
      assert(syncedSequenceId.isEmpty, "The pre-downgrade must strip the sequence pointer.")
      // Stock v1 generation continues from the migrated HWM (base = HWM + step), so a new
      // auto-generated id is serviceHwm + step -- well below the explicit data max. Had the
      // downgrade migrated the DATA max instead, this would be explicitId-derived (4097+).
      spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (100)")
      val newAutoId = readDeltaTable(tempPath).where("values = 100").select("ids").head().getLong(0)
      assert(newAutoId === v1Value,
        s"Post-downgrade auto id must continue from the SERVICE HWM (serviceHwm + step = " +
          s"$v1Value), got $newAutoId. A value >= $explicitId means the downgrade migrated the " +
          "table max instead of the service high-water mark (BUG).")
      assert(newAutoId < explicitId,
        s"Post-downgrade auto id $newAutoId must be strictly below the explicit data max " +
          s"$explicitId (else the downgrade scanned the data).")

      // 2. Re-opt-in -> CIC again: re-conversion is HWM-driven too, NOT a data scan. It mints one
      // fresh sequence seeded from the schema HWM (now `v1Value` from the stock write above), so
      // the next service id continues from there -- again below the explicit data max.
      val createsBeforeReconvert = localService.createSequenceCount
      spark.sql(cicFeatureOptInDdl)
      assert(localService.createSequenceCount === createsBeforeReconvert + 1,
        "Re-conversion must mint exactly one fresh sequence for the one identity column.")
      assert(syncedSequenceId.isDefined, "Re-conversion must re-stamp the sequence pointer.")
      withSQLConf(
          DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true",
          DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_RESERVE_DRIVER_INITIAL_SIZE.key ->
            reserveSize.toString) {
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (200)")
      }
      val cicAutoId = readDeltaTable(tempPath).where("values = 200").select("ids").head().getLong(0)
      assert(cicAutoId === reconvertedValue,
        s"Post-re-conversion service id must continue from the schema HWM (HWM + step = " +
          s"$reconvertedValue), got $cicAutoId. A value >= $explicitId means re-conversion " +
          "seeded from the data max instead of the high-water mark (BUG).")
      assert(cicAutoId < explicitId,
        s"Post-re-conversion service id $cicAutoId must be strictly below the explicit data max " +
          s"$explicitId (else re-conversion scanned the data).")

      // The explicit value survives the full CIC -> v1 -> CIC round-trip untouched, and no
      // generated id ever collided with it.
      assert(selectMaxId === explicitId,
        s"The explicit data max $explicitId must survive the round-trip untouched, " +
          s"got $selectMaxId.")
      assertCorrectIdentityColumn(readDeltaTable(tempPath).select("ids"), expectedSize = 6L)
    }
  }

  private val dropWithoutServiceConf =
    DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_DROP_WITHOUT_SERVICE.key

  test("DROP FEATURE without the service migrates the table max/min, not the service HWM") {
    // Mirror of "DROP FEATURE migrates the service high-water mark, not the table max/min":
    // with the escape-hatch conf on, the downgrade scans the data extreme (like SYNC) instead of
    // reserving from the service, so the migrated HWM is the DATA max, and neither reserveIds nor
    // dropSequence is called. GENERATED BY DEFAULT lets us insert an explicit id far above the
    // service HWM so the two migration sources are distinguishable.
    val step = 2L
    val start = 1L
    val reserveSize = 64L
    val serviceHwm = start + reserveSize * step
    // On the lattice (start=1, step=2 -> odd) so the scanned mark needs no rounding.
    val explicitId = serviceHwm * 1024L + 1L
    // The data max is the explicit id; stock v1 continues at dataMax + step.
    val v1Value = explicitId + step
    withTable("target") {
      withSQLConf(
          DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true",
          DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_RESERVE_DRIVER_INITIAL_SIZE.key ->
            reserveSize.toString) {
        spark.sql(createTargetTableStatement(Seq(
          s"ids BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH $start INCREMENT BY $step)",
          "values INT")))
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (1), (2), (3)")
        // Explicit id far above the service HWM (BY DEFAULT permits it). Touches no service.
        spark.sql(s"INSERT INTO delta.`$tempPath` (ids, values) VALUES ($explicitId, 99)")
      }
      assert(syncedSequenceId.isDefined, "Setup: a conf-on table must carry a sequenceId.")
      val droppedSequenceId = syncedSequenceId.get
      val serviceTableId =
        ConcurrentIdentityColumnSchema.sequenceServiceTableId(deltaLog.update().metadata)
      assert(selectMaxId === explicitId,
        s"Setup: the explicit id $explicitId must be the table max, got $selectMaxId.")
      assert(selectMaxId > serviceHwm,
        s"Setup: the table max $selectMaxId must sit above the service HWM $serviceHwm so the " +
          "two migration sources are distinguishable.")

      // DROP FEATURE with the escape hatch on: the downgrade scans the data, never the service.
      val reservesBefore = localService.reserveIdsCount
      val dropsBefore = localService.dropSequenceCount
      withSQLConf(dropWithoutServiceConf -> "true") {
        spark.sql(cicDropFeatureDdl)
      }
      assert(!deltaLog.update().protocol.isFeatureSupported(ConcurrentIdentityColumnsTableFeature),
        "DROP FEATURE must remove the CIC feature from the protocol.")
      assert(syncedSequenceId.isEmpty, "The pre-downgrade must strip the sequence pointer.")
      assert(localService.reserveIdsCount === reservesBefore,
        "The escape hatch must NOT reserve from the service during downgrade.")
      assert(localService.dropSequenceCount === dropsBefore,
        "The escape hatch must NOT drop the service sequence (it is left to service GC).")
      assert(localService.hasSequence(serviceTableId, droppedSequenceId),
        "The escape hatch leaves the orphaned sequence in the service (no dropSequence).")

      // Stock v1 continues from the migrated DATA max (dataMax + step), not the service HWM.
      spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (100)")
      val newAutoId = readDeltaTable(tempPath).where("values = 100").select("ids").head().getLong(0)
      assert(newAutoId === v1Value,
        s"Post-downgrade auto id must continue from the DATA max (explicitId + step = $v1Value), " +
          s"got $newAutoId. A value near ${serviceHwm + step} means the downgrade migrated the " +
          "service high-water mark instead of scanning the data (BUG).")
      assertCorrectIdentityColumn(readDeltaTable(tempPath).select("ids"), expectedSize = 5L)
    }
  }

  test("DROP FEATURE without the service succeeds even when the sequence is gone") {
    // The whole point of the escape hatch: leave the feature while the service is unavailable.
    // Simulate that by dropping the sequence out from under the table first, then downgrade with
    // the conf on. The default (service) path would fail trying to reserve from the missing
    // sequence; the escape hatch scans the data and succeeds.
    withTable("target") {
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(createTargetTableStatement(Seq(
          "ids BIGINT GENERATED ALWAYS AS IDENTITY",
          "values INT")))
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (10), (20), (30)")
      }
      assert(syncedSequenceId.isDefined, "Setup: a conf-on table must carry a sequenceId.")
      val sequenceId = syncedSequenceId.get
      val serviceTableId =
        ConcurrentIdentityColumnSchema.sequenceServiceTableId(deltaLog.update().metadata)
      val maxBefore = selectMaxId
      // Retire the sequence behind the table's back: the service can no longer serve it.
      localService.dropSequence(DropSequenceRequest(sequenceId, serviceTableId))
      assert(!localService.hasSequence(serviceTableId, sequenceId),
        "Setup: the sequence must be gone before the downgrade.")

      withSQLConf(dropWithoutServiceConf -> "true") {
        spark.sql(cicDropFeatureDdl)
      }

      assert(!deltaLog.update().protocol.isFeatureSupported(ConcurrentIdentityColumnsTableFeature),
        "DROP FEATURE must remove the CIC feature even with the sequence gone.")
      assert(syncedSequenceId.isEmpty, "The pre-downgrade must strip the sequence pointer.")
      // Stock identity continues past the already-written data (schema HWM from the scan).
      spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (40), (50)")
      assert(selectMaxId > maxBefore,
        s"Post-downgrade stock values must continue past $maxBefore, got $selectMaxId.")
      assertCorrectIdentityColumn(readDeltaTable(tempPath).select("ids"), expectedSize = 5L)
    }
  }

  test("DROP FEATURE without the service on an empty table writes no high-water mark") {
    // Empty-table edge case: with no rows the data scan finds no extreme, so syncIdentity leaves
    // the field unchanged (no delta.identity.highWaterMark). The downgrade must still strip the
    // pointer and touch no service, and the resulting stock column must generate from `start`.
    val start = 5L
    val step = 3L
    withTable("target") {
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(createTargetTableStatement(Seq(
          s"ids BIGINT GENERATED ALWAYS AS IDENTITY (START WITH $start INCREMENT BY $step)",
          "values INT")))
        // No INSERT: the table is empty, so the service was never reserved from.
      }
      assert(syncedSequenceId.isDefined, "Setup: a conf-on table must carry a sequenceId.")

      val reservesBefore = localService.reserveIdsCount
      val dropsBefore = localService.dropSequenceCount
      withSQLConf(dropWithoutServiceConf -> "true") {
        spark.sql(cicDropFeatureDdl)
      }

      assert(!deltaLog.update().protocol.isFeatureSupported(ConcurrentIdentityColumnsTableFeature),
        "DROP FEATURE must remove the CIC feature from the protocol.")
      assert(syncedSequenceId.isEmpty, "The pre-downgrade must strip the sequence pointer.")
      assert(localService.reserveIdsCount === reservesBefore,
        "The escape hatch must NOT reserve from the service, even on an empty table.")
      assert(localService.dropSequenceCount === dropsBefore,
        "The escape hatch must NOT drop the service sequence.")
      assert(
        IdentityColumn.getIdentityInfo(deltaLog.update().metadata.schema("ids")).highWaterMark
          .isEmpty,
        "An empty table has no data extreme, so the downgrade must write no high-water mark.")

      // Stock identity on the now-classic column starts from `start` (no HWM to continue past).
      spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (1)")
      val firstId = readDeltaTable(tempPath).where("values = 1").select("ids").head().getLong(0)
      assert(firstId === start,
        s"First stock value on an empty downgraded table must be START ($start), got $firstId.")
    }
  }

  test("a failed DROP TABLE does not retire the table's service sequences") {
    withTable("target") {
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(createTargetTableStatement(Seq(
          "ids BIGINT GENERATED ALWAYS AS IDENTITY",
          "values INT")))
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (1)")
      }
      val sequenceId = syncedSequenceId.getOrElse {
        fail("Setup: the CIC table must stamp a sequence on the identity column.")
      }
      val serviceTableId =
        ConcurrentIdentityColumnSchema.sequenceServiceTableId(deltaLog.update().metadata)
      val dropsBefore = localService.dropSequenceCount
      val injectedFailure = new IllegalStateException("injected catalog drop failure")

      // A mock is required to force the physical catalog drop to fail after metadata is read.
      val failingSessionCatalog = spy(spark.sessionState.catalog)
      doAnswer(_ => throw injectedFailure).when(failingSessionCatalog).dropTable(
        any[TableIdentifier], anyBoolean(), anyBoolean())
      val catalog = new V2SessionCatalog(failingSessionCatalog)

      val exception = intercept[IllegalStateException] {
        catalog.dropTable(Identifier.of(Array("default"), "target"))
      }

      assert(exception eq injectedFailure)
      assert(spark.catalog.tableExists("target"),
        "A failed catalog drop must leave the table live.")
      assert(localService.dropSequenceCount === dropsBefore,
        "A failed catalog drop must not attempt sequence retirement.")
      assert(localService.hasSequence(serviceTableId, sequenceId),
        "A failed catalog drop must leave the live table's sequence intact.")
    }
  }

  test("DROP TABLE of a non-CIC table calls no sequence service") {
    // Negative case: a plain (non-identity) Delta table must not reach the sequence service.
    withTable("target") {
      spark.sql(
        s"""CREATE TABLE target (id BIGINT, values INT)
           |USING DELTA
           |LOCATION '$tempPath'
           |""".stripMargin)
      spark.sql(s"INSERT INTO delta.`$tempPath` VALUES (1, 1)")
      val dropsBefore = localService.dropSequenceCount

      spark.sql("DROP TABLE target")

      assert(localService.dropSequenceCount === dropsBefore,
        "DROP TABLE of a table without sequence pointers must not call dropSequence.")
    }
  }

  private val tooManyColumnsError = "DELTA_CONCURRENT_IDENTITY_COLUMN_TOO_MANY_COLUMNS"

  private def identityColumnDefs(n: Int): Seq[String] =
    (1 to n).map(i => s"id$i BIGINT GENERATED ALWAYS AS IDENTITY") :+ "values INT"

  test("CREATE rejects a CIC table over the identity-column limit") {
    withTable("target") {
      withSQLConf(
          DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true",
          DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_MAX_COLUMNS_PER_TABLE.key -> "2") {
        val cause = cicReservationCause(intercept[Exception] {
          spark.sql(createTargetTableStatement(identityColumnDefs(3)))
        })
        checkErrorMatchPVals(
          cause,
          condition = tooManyColumnsError,
          parameters = Map("tableId" -> ".*", "numColumns" -> "3", "maxColumns" -> "2"))
      }
      assert(!spark.catalog.tableExists("target"),
        "A CREATE rejected over the limit must not leave a table behind.")
    }
  }

  test("CREATE at the identity-column limit succeeds") {
    withTable("target") {
      withSQLConf(
          DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true",
          DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_MAX_COLUMNS_PER_TABLE.key -> "3") {
        spark.sql(createTargetTableStatement(identityColumnDefs(3)))
        // All three identity columns are service-backed (the table-level invariant).
        Seq("id1", "id2", "id3").foreach { c =>
          assert(ConcurrentIdentityColumnSchema
            .getSequenceId(deltaLog.update().metadata.schema(c)).isDefined,
            s"Column $c at the limit must be stamped.")
        }
      }
    }
  }

  test("feature opt-in rejects a table over the identity-column limit") {
    withTable("target") {
      // Build a plain (stock) identity table with 3 identity columns, feature not yet on.
      spark.sql(
        s"""CREATE TABLE target (
           |  ${identityColumnDefs(3).mkString(",\n  ")})
           |USING DELTA
           |LOCATION '$tempPath'
           |tblproperties(
           |  ${TableFeatureProtocolUtils.propertyKey(IdentityColumnsTableFeature)} = 'enabled')
           |""".stripMargin)
      withSQLConf(
          DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true",
          DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_MAX_COLUMNS_PER_TABLE.key -> "2") {
        val tableId = deltaLog.update().metadata.id
        val cause = cicReservationCause(intercept[Exception] {
          spark.sql(cicFeatureOptInDdl)
        })
        checkError(
          cause,
          condition = tooManyColumnsError,
          sqlState = "54011",
          parameters = Map("tableId" -> tableId, "numColumns" -> "3", "maxColumns" -> "2"))
      }
      assert(!deltaLog.update().protocol.isFeatureSupported(ConcurrentIdentityColumnsTableFeature),
        "A conversion rejected over the limit must not add the feature.")
    }
  }

  private val killSwitchError = "DELTA_CONCURRENT_IDENTITY_COLUMN_DISABLED"

  test("kill switch blocks the feature opt-in conversion") {
    withTable("target") {
      createLegacyTableWithCicWithoutSequenceId(rows = Seq(10, 20))
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "false") {
        val cause = cicReservationCause(intercept[Exception] {
          spark.sql(cicFeatureOptInDdl)
        })
        checkError(
          cause,
          condition = killSwitchError,
          sqlState = "0A000",
          parameters = cause.getMessageParameters.asScala.toMap)
      }
      assert(syncedSequenceId.isEmpty,
        "A conversion blocked by the kill switch must not stamp.")
    }
  }

  test("kill switch blocks SYNC IDENTITY repair") {
    withTable("target") {
      spark.sql(createTargetTableStatement(Seq(
        "ids BIGINT GENERATED ALWAYS AS IDENTITY",
        "values INT")))
      val seqBefore = syncedSequenceId.get
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "false") {
        val cause = cicReservationCause(intercept[Exception] {
          spark.sql(s"ALTER TABLE delta.`$tempPath` ALTER COLUMN ids SYNC IDENTITY")
        })
        checkError(
          cause,
          condition = killSwitchError,
          sqlState = "0A000",
          parameters = cause.getMessageParameters.asScala.toMap)
      }
      assert(syncedSequenceId.get === seqBefore,
        "A repair blocked by the kill switch must not re-stamp.")
    }
  }


  test("kill switch leaves reads and the DROP FEATURE escape hatch working") {
    // The operational recovery path must work WHILE the switch is off: read the data,
    // drop the feature (returning the table to stock identity), and keep writing through
    // the stock path.
    withTable("target") {
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(createTargetTableStatement(Seq(
          "ids BIGINT GENERATED ALWAYS AS IDENTITY",
          "values INT")))
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (10), (20), (30)")
      }
      val maxBefore = selectMaxId

      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "false") {
        // Reads are unaffected.
        assert(readDeltaTable(tempPath).count() === 3L,
          "Reads must keep working under the kill switch.")
        // The escape hatch: leave the service backend entirely.
        spark.sql(cicDropFeatureDdl)
        assert(syncedSequenceId.isEmpty,
          "DROP FEATURE must work under the kill switch and strip the pointer.")
        // Stock identity writes work even with the switch still off.
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (40), (50)")
      }
      assert(selectMaxId > maxBefore,
        s"Post-escape stock values must continue past $maxBefore, got $selectMaxId.")
      assertCorrectIdentityColumn(readDeltaTable(tempPath).select("ids"), expectedSize = 5L)
    }
  }


  /**
   * Collect the CIC usage events of one `opType` emitted while running `f`, as parsed blobs.
   * The dashboard reads these opType strings and blob keys, so asserting on them here is what
   * keeps a rename from silently breaking a panel.
   */
  private def cicEvents(opType: String)(f: => Unit): Seq[Map[String, Any]] =
    Log4jUsageLogger.track(f)
      .filter { e =>
        e.metric == MetricDefinitions.EVENT_TAHOE.name && e.tags.get("opType").contains(opType)
      }
      .map(e => JsonUtils.fromJson[Map[String, Any]](e.blob))

  test("dropSequence event: DROP COLUMN reports its own retirement path") {
    withTable("target") {
      withSQLConf(
        DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true",
        DeltaSQLConf.DELTA_ALTER_TABLE_DROP_COLUMN_ENABLED.key -> "true") {
        spark.sql(createTargetTableStatement(Seq(
          "ids BIGINT GENERATED ALWAYS AS IDENTITY",
          "values INT")))
        spark.sql(
          s"ALTER TABLE delta.`$tempPath` SET TBLPROPERTIES ('delta.columnMapping.mode' = 'name')")
        spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (1)")

        val events = cicEvents(ConcurrentIdentityColumnObservability.opTypeDropSequence) {
          spark.sql(s"ALTER TABLE delta.`$tempPath` DROP COLUMN ids")
        }

        assert(events.size === 1, s"Expected exactly one dropSequence event, got $events.")
        assert(events.head("reason") ===
          ConcurrentIdentityColumnObservability.DropReason.DropColumn)
      }
    }
  }

  test("no dropSequence event when a non-CIC table is dropped") {
    withTable("target") {
      spark.sql(
        s"""CREATE TABLE target (id BIGINT, values INT)
           |USING DELTA
           |LOCATION '$tempPath'
           |""".stripMargin)
      spark.sql(s"INSERT INTO delta.`$tempPath` VALUES (1, 1)")

      val events = cicEvents(ConcurrentIdentityColumnObservability.opTypeDropSequence) {
        spark.sql("DROP TABLE target")
      }

      assert(events.isEmpty, s"A table with no sequence pointer must emit nothing, got $events.")
    }
  }

  test("refillFailed event: a failed service reserve is reported per occurrence") {
    withTable("target") {
      withSQLConf(DeltaSQLConf.CONCURRENT_IDENTITY_COLUMN_ENABLED.key -> "true") {
        spark.sql(createTargetTableStatement(Seq(
          "ids BIGINT GENERATED ALWAYS AS IDENTITY",
          "values INT")))
        // Fail every reserve from the first one, so the driver's background refill fails.
        localService.failReserveIdsStartingAt(1L)

        val events = cicEvents(ConcurrentIdentityColumnObservability.opTypeRefillFailed) {
          intercept[Exception] {
            spark.sql(s"INSERT INTO delta.`$tempPath` (values) VALUES (1)")
          }
        }

        assert(events.nonEmpty, "A failed refill must emit refillFailed.")
        // errorClass, not the message: the message interpolates table and sequence ids.
        assert(events.head.contains("errorClass"),
          s"refillFailed must carry errorClass, got ${events.head.keys}.")
        assert(events.head.contains("sequenceId") && events.head.contains("tableId"))
      }
    }
  }
}
