/*
 * Copyright (2026) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.apache.spark.sql.delta

import scala.language.postfixOps

import org.apache.spark.sql.delta.sources.DeltaSQLConf
import org.apache.spark.sql.delta.cic.{
  CreateSequenceRequest,
  DropSequenceRequest,
  LocalIdentitySequenceService,
  ReserveIdsRequest,
  ReserveIdsResponse
}

import org.apache.spark.sql.Row
import org.apache.spark.sql.functions._

class ConcurrentIdentityColumnMergeCoreSuite extends ConcurrentIdentityColumnSuiteBase
  with ConcurrentIdentityColumnMergeCoreTests

// NOTE on fixtures: sources are repartition(1) throughout these suites. A single partition
// keeps the per-partition identity generator contiguous, so a count-based service reservation
// is never overshot by partition striding; the service backend fails loud on such an overshoot
// (unlike the removed metadata-domain backend, which tolerated it), and that behavior has
// dedicated fail-fast and reserve-more tests in ConcurrentIdentityColumnServiceBackendSuite.
trait ConcurrentIdentityColumnMergeCoreTests { self: ConcurrentIdentityColumnSuiteBase =>

  import testImplicits._

  test("single merge") {
    withTable("target") {
      spark.sql(createTargetTableStatement(Seq(
        "ids BIGINT GENERATED ALWAYS AS IDENTITY",
        "values INT")))
      withTempView("source") {
        val source = Seq(10, 20, 30, 40, 50, 60, 70, 80, 90, 100)
        source.toDF("values").repartition(1).createOrReplaceTempView("source")

        executeMerge(
          tgt = s"delta.`$tempPath` AS t",
          src = "source s",
          cond = "t.values = s.values",
          clauses = insert("(values) VALUES (s.values)"))

        val targetDf = readDeltaTable(tempPath)
        assertCorrectIdentityColumn(
          targetDf.select("ids"),
          expectedSize = source.size,
          start = 1, step = 1,
          expectedMin = 1,
          expectedMax = Long.MaxValue)
        checkAnswer(targetDf.select("values").sort(col("values")), source.toDF().sort())
      }
    }
  }

  test("single large merge") {
    withTable("target") {
      spark.sql(createTargetTableStatement(Seq(
        "ids BIGINT GENERATED ALWAYS AS IDENTITY",
        "values INT")))
      withTempView("source") {
        val source = Seq.range(0, 1000000)
        source.toDF("values").repartition(1).createOrReplaceTempView("source")

        executeMerge(
          tgt = s"delta.`$tempPath` AS t",
          src = "source s",
          cond = "t.values = s.values",
          clauses = insert("(values) VALUES (s.values)"))

        val targetDf = readDeltaTable(tempPath)
        assertCorrectIdentityColumn(
          targetDf.select("ids"),
          expectedSize = source.size,
          start = 1, step = 1,
          expectedMin = 1,
          expectedMax = Long.MaxValue)
        checkAnswer(targetDf.select("values").sort(col("values")), source.toDF().sort())
      }
    }
  }

  test("merge with generated and non-generated columns") {
    withTable("target") {
      spark.sql(createTargetTableStatement(Seq(
        // Use idsZ and idsA to force a correct sorting.
        "idsZ BIGINT GENERATED ALWAYS AS IDENTITY",
        "idsA BIGINT GENERATED BY DEFAULT AS IDENTITY",
        "values INT")))
      withTempView("source") {
        val source = Seq(
          (10, -1), (20, -2), (30, -3), (40, -4), (50, -5),
          (60, -6), (70, -7), (80, -8), (90, -9))
        source.toDF("values", "ids").repartition(1).createOrReplaceTempView("source")

        executeMerge(
          tgt = s"delta.`$tempPath` AS t",
          src = "source s",
          cond = "t.values = s.values",
          clauses = insert("(values, idsA) VALUES (s.values, s.ids)"))

        val targetDf = readDeltaTable(tempPath)
        assertCorrectIdentityColumn(
          targetDf.select("idsZ"),
          expectedSize = source.size,
          start = 1, step = 1,
          expectedMin = 1,
          expectedMax = Long.MaxValue)
        assertCorrectIdentityColumn(
          targetDf.select("idsA"),
          expectedSize = source.size,
          expectedMin = -9,
          expectedMax = -1)
        checkAnswer(
          targetDf.select("values", "idsA").sort(col("values")),
          source.toDF("values", "ids").sort(col("values")))
      }
    }
  }

  test("two merges consecutively") {
    withTable("target") {
      spark.sql(createTargetTableStatement(Seq(
        "ids BIGINT GENERATED ALWAYS AS IDENTITY",
        "values INT")))
      withTempView("source1", "source2") {
        val source1 = Seq(10, 20, 30, 40, 50, 60, 70, 80, 90)
        source1.toDF("values").repartition(1).createOrReplaceTempView("source1")
        val source2 = Seq(100, 200, 300, 400, 500, 600, 700, 800, 900, 1000)
        source2.toDF("values").repartition(1).createOrReplaceTempView("source2")

        // Execute first merge
        executeMerge(
          tgt = s"delta.`$tempPath` AS t",
          src = "source1 s",
          cond = "t.values = s.values",
          clauses = insert("(values) VALUES (s.values)"))
        // Execute second merge
        executeMerge(
          tgt = s"delta.`$tempPath` AS t",
          src = "source2 s",
          cond = "t.values = s.values",
          clauses = insert("(values) VALUES (s.values)"))

        val targetDf = readDeltaTable(tempPath)
        assertCorrectIdentityColumn(
          targetDf.select("ids"),
          expectedSize = source1.size + source2.size,
          start = 1, step = 1,
          expectedMin = 1,
          expectedMax = Long.MaxValue)
        checkAnswer(
          targetDf.select("values").sort(col("values")), (source1 ++ source2).toDF().sort())
      }
    }
  }

  test("two merges with two identity columns") {
    withTable("target") {
      spark.sql(createTargetTableStatement(Seq(
        "ids1 BIGINT GENERATED ALWAYS AS IDENTITY",
        "ids2 BIGINT GENERATED ALWAYS AS IDENTITY (START WITH -100 INCREMENT BY -10)",
        "values INT"
      )))
      withTempView("source1", "source2") {
        val source1 = Seq(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)
        source1.toDF("values").repartition(1).createOrReplaceTempView("source1")
        val source2 = Seq(100, 200, 300, 400, 500, 600, 700, 800, 900,
          1000, 1100, 1200, 1300, 1400, 1500)
        source2.toDF("values").repartition(1).createOrReplaceTempView("source2")

        // Execute first merge
        executeMerge(
          tgt = s"delta.`$tempPath` AS t",
          src = "source1 s",
          cond = "t.values = s.values",
          clauses = insert("(values) VALUES (s.values)"))
        // Execute second merge
        executeMerge(
          tgt = s"delta.`$tempPath` AS t",
          src = "source2 s",
          cond = "t.values = s.values",
          clauses = insert("(values) VALUES (s.values)"))

        val targetDf = readDeltaTable(tempPath)
        assertCorrectIdentityColumn(
          targetDf.select("ids1"),
          expectedSize = source1.size + source2.size,
          start = 1, step = 1,
          expectedMin = 1,
          expectedMax = Long.MaxValue)
        assertCorrectIdentityColumn(
          targetDf.select("ids2"),
          expectedSize = source1.size + source2.size,
          start = -100, step = -10,
          expectedMin = Long.MinValue, expectedMax = -100)
        checkAnswer(
          targetDf.select("values").sort(col("values")), (source1 ++ source2).toDF().sort())
      }
    }
  }

  test("calculating next high watermark overflows") {
    withTable("target") {
      spark.sql(createTargetTableStatement(Seq(
        s"ids BIGINT GENERATED ALWAYS AS IDENTITY " +
          s"(START WITH ${Long.MaxValue - 10} INCREMENT BY 100)",
        "values INT")))
      withTempView("source") {
        val source = Seq(10, 20, 30, 40, 50, 60, 70, 80, 90, 100)
        source.toDF("values").repartition(1).createOrReplaceTempView("source")

        // The service stub's checked arithmetic rejects a reservation that would overflow the
        // counter. On the simple service backend each executor task reserves its own range on
        // demand inside the write job, so the ArithmeticException surfaces from the task and Spark
        // wraps it in a SparkException; assert on the cause chain rather than the bare type.
        val e = intercept[Exception] {
          executeMerge(
            tgt = s"delta.`$tempPath` AS t",
            src = "source s",
            cond = "t.values = s.values",
            clauses = insert("(values) VALUES (s.values)"))
        }
        assert(causeChain(e).exists(_.isInstanceOf[java.lang.ArithmeticException]),
          s"expected an ArithmeticException in the cause chain; got: ${causeChainMessages(e)}")
        assert(messageChainContains(e, "long overflow"),
          s"expected a long-overflow failure; got: ${causeChainMessages(e)}")
      }
    }
  }
}

