/*
 * Copyright (2021) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.delta

import java.util.UUID

import org.apache.spark.sql.delta.actions.Protocol
import org.apache.spark.sql.delta.sources.{DeltaSourceUtils, DeltaSQLConf}
import org.apache.spark.sql.delta.test.DeltaSQLCommandTest

import org.apache.spark.SparkConf
import org.apache.spark.sql.{AnalysisException, QueryTest, Row}
import org.apache.spark.sql.catalyst.TableIdentifier
import org.apache.spark.sql.test.SharedSparkSession
import org.apache.spark.sql.types.{LongType, StructField}

/**
 * Tests that `CREATE TABLE ... GENERATED [ALWAYS|BY DEFAULT] AS IDENTITY` SQL DDL works for
 * Delta tables. Spark 4.0+ parses the SQL natively, stores identity info in StructField metadata
 * under `identity.*` keys, and routes it to the V2 catalog only if the catalog advertises the
 * `SUPPORTS_CREATE_TABLE_WITH_IDENTITY_COLUMNS` capability. Delta's catalog opts in and translates
 * Spark's metadata keys into Delta's own `delta.identity.*` keys.
 */
trait IdentityColumnSqlDDLSuiteBase
    extends QueryTest
    with SharedSparkSession
    with DeltaSQLCommandTest {

  protected override def sparkConf: SparkConf =
    super.sparkConf.set(DeltaSQLConf.DELTA_IDENTITY_COLUMN_ENABLED.key, "true")

  private def getRandomTableName: String =
    s"identity_sql_${UUID.randomUUID()}".replaceAll("-", "_")

  private def getDeltaSchema(tableName: String) =
    DeltaLog.forTable(spark, TableIdentifier(tableName)).snapshot.schema

  private def assertIsDeltaIdentity(
      field: StructField,
      expectedStart: Long,
      expectedStep: Long,
      expectedAllowExplicitInsert: Boolean): Unit = {
    assert(field.dataType === LongType, s"${field.name} should be BIGINT")
    val md = field.metadata
    assert(md.contains(DeltaSourceUtils.IDENTITY_INFO_START), s"missing delta.identity.start")
    assert(md.contains(DeltaSourceUtils.IDENTITY_INFO_STEP), s"missing delta.identity.step")
    assert(
      md.contains(DeltaSourceUtils.IDENTITY_INFO_ALLOW_EXPLICIT_INSERT),
      "missing delta.identity.allowExplicitInsert")
    assert(md.getLong(DeltaSourceUtils.IDENTITY_INFO_START) === expectedStart)
    assert(md.getLong(DeltaSourceUtils.IDENTITY_INFO_STEP) === expectedStep)
    assert(
      md.getBoolean(DeltaSourceUtils.IDENTITY_INFO_ALLOW_EXPLICIT_INSERT)
        === expectedAllowExplicitInsert)
    // Spark's own identity keys should not leak into committed Delta metadata.
    assert(!md.contains("identity.start"))
    assert(!md.contains("identity.step"))
    assert(!md.contains("identity.allowExplicitInsert"))
  }

  test("CREATE TABLE with all four GENERATED AS IDENTITY flavors") {
    val t = getRandomTableName
    withTable(t) {
      sql(
        s"""CREATE TABLE $t (
           |  id_col1 BIGINT GENERATED ALWAYS AS IDENTITY,
           |  id_col2 BIGINT GENERATED ALWAYS AS IDENTITY (START WITH -1 INCREMENT BY 1),
           |  id_col3 BIGINT GENERATED BY DEFAULT AS IDENTITY,
           |  id_col4 BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH -1 INCREMENT BY 1),
           |  value INT
           |) USING delta
           |""".stripMargin)

      val schema = getDeltaSchema(t)
      assertIsDeltaIdentity(schema("id_col1"),
        expectedStart = 1L, expectedStep = 1L, expectedAllowExplicitInsert = false)
      assertIsDeltaIdentity(schema("id_col2"),
        expectedStart = -1L, expectedStep = 1L, expectedAllowExplicitInsert = false)
      assertIsDeltaIdentity(schema("id_col3"),
        expectedStart = 1L, expectedStep = 1L, expectedAllowExplicitInsert = true)
      assertIsDeltaIdentity(schema("id_col4"),
        expectedStart = -1L, expectedStep = 1L, expectedAllowExplicitInsert = true)

      // The IDENTITY columns feature should be auto-enabled on commit.
      val protocol: Protocol =
        DeltaLog.forTable(spark, TableIdentifier(t)).snapshot.protocol
      assert(protocol.isFeatureSupported(IdentityColumnsTableFeature),
        s"identity columns table feature not enabled; protocol=$protocol")

      sql(s"INSERT INTO $t (value) VALUES (10), (20), (30)")
      val rows = sql(s"SELECT id_col1, id_col2, id_col3, id_col4, value FROM $t ORDER BY value")
        .collect()
      assert(rows.length === 3)
      // ALWAYS columns must be system-generated; verify values monotonically increase per
      // configured (start, step).
      val col1 = rows.map(_.getLong(0)).toSeq
      val col2 = rows.map(_.getLong(1)).toSeq
      val col3 = rows.map(_.getLong(2)).toSeq
      val col4 = rows.map(_.getLong(3)).toSeq
      assert(col1.distinct.size === 3 && col1.forall(_ >= 1L))
      assert(col2.distinct.size === 3 && col2.forall(_ >= -1L))
      assert(col3.distinct.size === 3 && col3.forall(_ >= 1L))
      assert(col4.distinct.size === 3 && col4.forall(_ >= -1L))
    }
  }

  test("INSERT into GENERATED ALWAYS AS IDENTITY column with explicit value is rejected") {
    val t = getRandomTableName
    withTable(t) {
      sql(
        s"""CREATE TABLE $t (
           |  id BIGINT GENERATED ALWAYS AS IDENTITY,
           |  value INT
           |) USING delta
           |""".stripMargin)
      val ex = intercept[Exception] {
        sql(s"INSERT INTO $t VALUES (100, 1)")
      }
      assert(
        Option(ex.getMessage).getOrElse("")
          .contains("Providing values for GENERATED ALWAYS AS IDENTITY"),
        s"unexpected error: ${ex.getMessage}")
    }
  }

  test("INSERT into GENERATED BY DEFAULT AS IDENTITY column with explicit value is allowed") {
    val t = getRandomTableName
    withTable(t) {
      sql(
        s"""CREATE TABLE $t (
           |  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
           |  value INT
           |) USING delta
           |""".stripMargin)
      sql(s"INSERT INTO $t VALUES (100, 1)")
      sql(s"INSERT INTO $t (value) VALUES (2)")
      val rows = sql(s"SELECT id, value FROM $t ORDER BY value").collect()
      assert(rows.length === 2)
      assert(rows(0) === Row(100L, 1))
      // The generated row must have a non-null auto-assigned identity value (Delta does not
      // advance the high water mark on explicit inserts into BY DEFAULT identity columns).
      assert(!rows(1).isNullAt(0))
    }
  }

  test("identity column on non-BIGINT type is rejected") {
    val t = getRandomTableName
    withTable(t) {
      val ex = intercept[Exception] {
        sql(s"""CREATE TABLE $t (id INT GENERATED ALWAYS AS IDENTITY) USING delta""")
      }
      val msg = Option(ex.getMessage).getOrElse("")
      assert(msg.toUpperCase(Locale.ROOT).contains("UNSUPPORTED") ||
        msg.toLowerCase(Locale.ROOT).contains("identity"), s"unexpected error: $msg")
    }
  }

  test("identity column on a partition column is rejected") {
    val t = getRandomTableName
    withTable(t) {
      val ex = intercept[Exception] {
        sql(
          s"""CREATE TABLE $t (
             |  id BIGINT GENERATED ALWAYS AS IDENTITY,
             |  value INT
             |) USING delta
             |PARTITIONED BY (id)
             |""".stripMargin)
      }
      assert(Option(ex.getMessage).getOrElse("").toLowerCase(Locale.ROOT).contains("identity"))
    }
  }

  test("INCREMENT BY 0 is rejected") {
    val t = getRandomTableName
    withTable(t) {
      val ex = intercept[Exception] {
        sql(
          s"""CREATE TABLE $t (
             |  id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 0)
             |) USING delta
             |""".stripMargin)
      }
      val msg = Option(ex.getMessage).getOrElse("")
      assert(msg.contains("step") || msg.toLowerCase(Locale.ROOT).contains("increment"),
        s"unexpected error: $msg")
    }
  }

  test("REPLACE TABLE swaps in an identity column") {
    val t = getRandomTableName
    withTable(t) {
      sql(s"""CREATE TABLE $t (id BIGINT, value INT) USING delta""")
      sql(
        s"""REPLACE TABLE $t (
           |  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
           |  value INT
           |) USING delta
           |""".stripMargin)
      val schema = getDeltaSchema(t)
      assertIsDeltaIdentity(schema("id"),
        expectedStart = 1L, expectedStep = 1L, expectedAllowExplicitInsert = true)
    }
  }

  // CTAS with an explicit schema (including identity columns) is rejected by Spark's parser
  // ("Schema may not be specified in a Create Table As Select (CTAS) statement"), so SQL-level
  // CTAS with identity is unsupported upstream. We do not add a Delta-specific test here.
}

class IdentityColumnSqlDDLSuite extends IdentityColumnSqlDDLSuiteBase
