package io.delta.flink.table;

import io.unitycatalog.client.ApiClient;
import io.unitycatalog.client.ApiException;
import io.unitycatalog.client.api.TablesApi;
import io.unitycatalog.client.api.TemporaryCredentialsApi;
import io.unitycatalog.client.model.GenerateTemporaryTableCredential;
import io.unitycatalog.client.model.TableInfo;
import io.unitycatalog.client.model.TableOperation;
import io.unitycatalog.client.model.TemporaryCredentials;
import java.net.URI;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * A {@code RESTCatalog} is a {@link Catalog} implementation that interacts with an external catalog
 * service via REST APIs.
 *
 * <p>This catalog resolves table metadata and access credentials by communicating with a remote
 * catalog endpoint. It is typically used in environments where table discovery, authorization, and
 * credential issuance are managed centrally by a service rather than through filesystem-based
 * catalogs.
 *
 * <p>The catalog uses:
 *
 * <ul>
 *   <li>a REST endpoint to load table metadata (e.g., storage location, table identifiers), and
 *   <li>temporary credentials generated by the catalog service to access underlying storage.
 * </ul>
 *
 * <p>Authentication to the catalog service is performed using a bearer token supplied at
 * construction time. The token is attached to all outgoing REST requests.
 */
public class RESTCatalog implements Catalog {

  private static Logger LOG = LoggerFactory.getLogger(RESTCatalog.class);

  public static String CATALOG_ENDPOINT = "catalog.endpoint";
  public static String CATALOG_TOKEN = "catalog.token";

  private final URI catalogEndpoint;
  private final String catalogToken;

  /**
   * Lazily initialized API client used to communicate with the catalog service. This field is
   * marked transient to avoid serialization issues in distributed environments.
   */
  protected transient ApiClient apiClient;

  /**
   * Creates a {@code RESTCatalog} with the given endpoint and authentication token.
   *
   * @param endpoint the catalog REST endpoint URI as a string
   * @param token a bearer token used to authenticate REST requests
   */
  public RESTCatalog(String endpoint, String token) {
    this.catalogEndpoint = URI.create(endpoint);
    this.catalogToken = token;
  }

  /**
   * Returns the catalog REST endpoint.
   *
   * @return the catalog endpoint URI
   */
  public URI getCatalogEndpoint() {
    return catalogEndpoint;
  }

  /**
   * Returns the authentication token used for catalog access.
   *
   * @return the catalog bearer token
   */
  public String getCatalogToken() {
    return catalogToken;
  }

  /**
   * Lazily initialize an {@link ApiClient} for communicating with the catalog service.
   *
   * @return an initialized {@link ApiClient}
   */
  protected ApiClient getApiClient() {
    if (apiClient == null) {
      apiClient =
          new ApiClient()
              .setScheme(catalogEndpoint.getScheme())
              .setHost(catalogEndpoint.getHost())
              .setPort(catalogEndpoint.getPort())
              .setRequestInterceptor(
                  request -> request.header("Authorization", "Bearer " + catalogToken));
    }
    return apiClient;
  }

  /**
   * Loads table metadata from the remote catalog.
   *
   * <p>This method retrieves table information via the catalog REST API and resolves the table
   * storage location into a normalized {@link URI}. The returned {@link TableBrief} contains the
   * table UUID and resolved storage path.
   *
   * @param tableId the logical identifier of the table
   * @return a {@link TableBrief} describing the resolved table
   * @throws RuntimeException if the table cannot be loaded due to API or network errors
   */
  @Override
  public TableBrief getTable(String tableId) {
    TablesApi tablesApi = new TablesApi(getApiClient());
    try {
      TableInfo tableInfo = tablesApi.getTable(tableId);
      TableBrief brief = new TableBrief();
      brief.tablePath =
          AbstractKernelTable.normalize(
              URI.create(Objects.requireNonNull(tableInfo.getStorageLocation())));
      brief.uuid = tableInfo.getTableId();
      LOG.debug("Loaded table with UUID {} at {}", brief.uuid, brief.tablePath);
      return brief;
    } catch (ApiException e) {
      throw new RuntimeException(e);
    }
  }

  /**
   * Retrieves temporary credentials required to access the underlying storage for the given table.
   *
   * <p>This implementation requests short-lived credentials from the catalog service that are
   * scoped to the specified table and operation type (read/write).
   *
   * <p>TODO: Currently, only AWS temporary credentials are supported. The returned configuration
   * map contains Hadoop-compatible S3A credential keys.
   *
   * @param tableId the table identifier for which credentials are requested
   * @return a map of filesystem configuration properties containing temporary credentials
   * @throws RuntimeException if credential generation fails due to API or network errors
   */
  @Override
  public Map<String, String> getCredentials(String tableId) {
    try {
      TemporaryCredentialsApi credentialsApi = new TemporaryCredentialsApi(getApiClient());
      TemporaryCredentials credentials =
          credentialsApi.generateTemporaryTableCredentials(
              new GenerateTemporaryTableCredential()
                  .tableId(tableId)
                  .operation(TableOperation.READ_WRITE));

      Map<String, String> result = new HashMap<>();

      // AWS credentials
      // TODO: Add Azure and GCP credential support
      if (credentials.getAwsTempCredentials() != null) {
        result.put("fs.s3a.access.key", credentials.getAwsTempCredentials().getAccessKeyId());
        result.put("fs.s3a.secret.key", credentials.getAwsTempCredentials().getSecretAccessKey());
        result.put("fs.s3a.session.token", credentials.getAwsTempCredentials().getSessionToken());
      }
      return result;
    } catch (ApiException e) {
      throw new RuntimeException(e);
    }
  }
}
