package io.delta.kernel.commit;

public enum TableManagementOperation {
  FILESYSTEM_MANAGED_CREATE,
  FILESYSTEM_MANAGED_WRITE,
  FILESYSTEM_MANGED_UPGRADE_TO_CATALOG_MANAGED,
  CATALOG_MANAGED_CREATE,
  CATALOG_MANAGED_WRITE,
  CATALOG_MANAGED_DISOWN,
}
