name: Add new and updated issues to Needs Review [DISABLED]

on:
# manual-only, auto triggers removed
  workflow_dispatch:


jobs:
  automate-new-updated-issues:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: alex-page/github-project-automation-plus@bb266ff4dde9242060e2d5418e120a133586d488 # v0.8.1
      with:
        project: oss-delta-issues
        column: Needs Review
        repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_TOKEN }}
