name: "Kernel Unity Catalog"
on:
  push:
    paths:
      - 'build.sbt'
      - 'version.sbt'
      - 'kernel/**/*.scala'
      - 'kernel/**/*.java'
      - 'storage/**/*.scala'
      - 'storage/**/*.java'
      - '.github/workflows/kernel_unitycatalog_test.yaml'
  pull_request:
    paths:
      - 'build.sbt'
      - 'version.sbt'
      - 'kernel/**/*.scala'
      - 'kernel/**/*.java'
      - 'storage/**/*.scala'
      - 'storage/**/*.java'
      - '.github/workflows/kernel_unitycatalog_test.yaml'
jobs:
  test:
    name: "Kernel Unity Catalog Tests"
    runs-on: ubuntu-24.04
    env:
      SCALA_VERSION: 2.13.16
      UNITY_CATALOG_VERSION: 0.5.0-SNAPSHOT
    steps:
      - uses: actions/checkout@v3
      - name: install java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Setup Unity Catalog for testing
        run: |
          git clone --depth 1 --branch atomic-rtas https://github.com/TimothyW553/unitycatalog.git /tmp/unitycatalog
          cd /tmp/unitycatalog
          export COURSIER_PARALLEL_DOWNLOAD_COUNT=1
          ./build/sbt "set Global / concurrentRestrictions := Seq(Tags.limitAll(1))" "set client / Compile / packageDoc / publishArtifact := false" client/generate client/publishM2
          ./build/sbt "set Global / concurrentRestrictions := Seq(Tags.limitAll(1))" "set server / Compile / packageDoc / publishArtifact := false" server/publishM2
          ./build/sbt "set Global / concurrentRestrictions := Seq(Tags.limitAll(1))" "set spark / Compile / packageDoc / publishArtifact := false" spark/publishM2
      - name: Run Unity tests with coverage
        run: |
          ./build/sbt "++ ${{ env.SCALA_VERSION }}" clean coverage kernelUnityCatalog/test coverageAggregate coverageOff -v
