name: "Kernel Unity Catalog"
on:
  push:
    branches: [ds-11122025]
  pull_request:
    branches: [ds-11122025]
jobs:
  test:
    name: "Kernel Unity Catalog Tests"
    runs-on: ubuntu-24.04
    env:
      SCALA_VERSION: 2.13.16
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: technote-space/get-diff-action@623b016c454ae55181c010cb611bd5d7028102c9 # v4.2.0
      id: git-diff
      with:
        PATTERNS: |
          build.sbt
          version.sbt
          unity/**
          kernel/**
          storage/**
          .github/workflows/unity_test.yaml
    - name: install java
      uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
      with:
        distribution: "zulu"
        java-version: "11"
      if: steps.git-diff.outputs.diff
    - name: Run Unity tests with coverage
      run: |
        ./build/sbt "++ ${{ env.SCALA_VERSION }}" clean coverage kernelUnityCatalog/test coverageAggregate coverageOff -v
      if: steps.git-diff.outputs.diff
