name: "Kernel Unity Catalog"
on:
  push:
    paths:
      - 'build.sbt'
      - 'version.sbt'
      - 'kernel/**/*.scala'
      - 'kernel/**/*.java'
      - 'storage/**/*.scala'
      - 'storage/**/*.java'
      - '.github/workflows/kernel_unitycatalog_test.yaml'
  pull_request:
    paths:
      - 'build.sbt'
      - 'version.sbt'
      - 'kernel/**/*.scala'
      - 'kernel/**/*.java'
      - 'storage/**/*.scala'
      - 'storage/**/*.java'
      - '.github/workflows/kernel_unitycatalog_test.yaml'
jobs:
  test:
    name: "Kernel Unity Catalog Tests"
    runs-on: ubuntu-24.04
    env:
      SCALA_VERSION: 2.13.16
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: install java
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Run Unity tests with coverage
        run: |
          ./build/sbt "++ ${{ env.SCALA_VERSION }}" clean coverage kernelUnityCatalog/test coverageAggregate coverageOff -v
