name: "Delta Spark Tests"
on:
  push:
    branches: [branch-3.0]
  pull_request:
    branches: [branch-3.0]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # These Scala versions must match those in the build.sbt
        scala: [2.12.17, 2.13.8]
    env:
      SCALA_VERSION: ${{ matrix.scala }}
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: technote-space/get-diff-action@623b016c454ae55181c010cb611bd5d7028102c9 # v4.2.0
      id: git-diff
      with:
        PATTERNS: |
          **
          !kernel/**
          !connectors/**
    - name: install java
      uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
      with:
        distribution: "zulu"
        java-version: "8"
    - name: Cache Scala, SBT
      uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
      with:
        path: |
          ~/.sbt
          ~/.ivy2
          ~/.cache/coursier
         # Change the key if dependencies are changed. For each key, GitHub Actions will cache the
          # the above directories when we use the key for the first time. After that, each run will
          # just use the cache. The cache is immutable so we need to use a new key when trying to
          # cache new stuff.
        key: delta-sbt-cache-spark3.2-scala${{ matrix.scala }}
    - name: Run Scala/Java and Python tests
      run: |
        python3 run-tests.py --group spark
        cd examples/scala && build/sbt "++ $SCALA_VERSION compile"
      if: steps.git-diff.outputs.diff
