name: "Unidoc"
on: [push, pull_request]
jobs:
  build:
    name: "U: Scala ${{ matrix.scala }}"
    runs-on: ubuntu-24.04
    env:
      UNITY_CATALOG_VERSION: 0.5.0-SNAPSHOT
    strategy:
      matrix:
        # These Scala versions must match those in the build.sbt
        scala: [2.13.16]
    steps:
      - name: install java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: actions/checkout@v3
      - name: Set up pinned Unity Catalog locally
        run: bash project/scripts/setup_unitycatalog_main.sh
      - name: generate unidoc
        run: build/sbt "++ ${{ matrix.scala }}" unidoc
