  name: "Unidoc"
  on: [push, pull_request]
  jobs:
    build:
      name: "U: Scala ${{ matrix.scala }}"
      runs-on: ubuntu-24.04
      strategy:
        matrix:
          # These Scala versions must match those in the build.sbt
          scala: [2.13.16]
      steps:
        - name: install java
          uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
          with:
            distribution: "zulu"
            java-version: "17"
        - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        - name: generate unidoc
          run: build/sbt "++ ${{ matrix.scala }}" unidoc
