/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file contains code from the Apache Spark project (original license above).
 * It contains modifications, which are licensed as follows:
 */

/*
 * Copyright (2021) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.delta.logging

import org.apache.spark.internal.LogKeyShims

/**
 * Various keys used for mapped diagnostic contexts(MDC) in logging. All structured logging keys
 * should be defined here for standardization.
 */
object LogKeys {
  case object ACCUMULATOR_ID extends LogKeyShims
  case object ACTUAL_NUM_FILES extends LogKeyShims
  case object ACTUAL_PARTITION_COLUMN extends LogKeyShims
  case object ADDED_JARS extends LogKeyShims
  case object AGGREGATE_FUNCTIONS extends LogKeyShims
  case object ALPHA extends LogKeyShims
  case object ANALYSIS_ERROR extends LogKeyShims
  case object APP_ATTEMPT_ID extends LogKeyShims
  case object APP_ATTEMPT_SHUFFLE_MERGE_ID extends LogKeyShims
  case object APP_DESC extends LogKeyShims
  case object APP_EXECUTOR_ID extends LogKeyShims
  case object APP_ID extends LogKeyShims
  case object APP_NAME extends LogKeyShims
  case object APP_STATE extends LogKeyShims
  case object ARGS extends LogKeyShims
  case object AUTH_ENABLED extends LogKeyShims
  case object BACKUP_FILE extends LogKeyShims
  case object BARRIER_EPOCH extends LogKeyShims
  case object BARRIER_ID extends LogKeyShims
  case object BATCH_ID extends LogKeyShims
  case object BATCH_NAME extends LogKeyShims
  case object BATCH_TIMESTAMP extends LogKeyShims
  case object BATCH_WRITE extends LogKeyShims
  case object BIND_ADDRESS extends LogKeyShims
  case object BLOCK_ID extends LogKeyShims
  case object BLOCK_IDS extends LogKeyShims
  case object BLOCK_MANAGER_ID extends LogKeyShims
  case object BLOCK_MANAGER_IDS extends LogKeyShims
  case object BLOCK_TYPE extends LogKeyShims
  case object BOOT extends LogKeyShims
  case object BOOTSTRAP_TIME extends LogKeyShims
  case object BROADCAST extends LogKeyShims
  case object BROADCAST_ID extends LogKeyShims
  case object BROADCAST_OUTPUT_STATUS_SIZE extends LogKeyShims
  case object BUCKET extends LogKeyShims
  case object BYTECODE_SIZE extends LogKeyShims
  case object CACHED_TABLE_PARTITION_METADATA_SIZE extends LogKeyShims
  case object CACHE_AUTO_REMOVED_SIZE extends LogKeyShims
  case object CACHE_UNTIL_HIGHEST_CONSUMED_SIZE extends LogKeyShims
  case object CACHE_UNTIL_LAST_PRODUCED_SIZE extends LogKeyShims
  case object CALL_SITE_LONG_FORM extends LogKeyShims
  case object CALL_SITE_SHORT_FORM extends LogKeyShims
  case object CATALOG_NAME extends LogKeyShims
  case object CATEGORICAL_FEATURES extends LogKeyShims
  case object CHECKPOINT_FILE extends LogKeyShims
  case object CHECKPOINT_LOCATION extends LogKeyShims
  case object CHECKPOINT_PATH extends LogKeyShims
  case object CHECKPOINT_ROOT extends LogKeyShims
  case object CHECKPOINT_TIME extends LogKeyShims
  case object CHOSEN_WATERMARK extends LogKeyShims
  case object CLASSIFIER extends LogKeyShims
  case object CLASS_LOADER extends LogKeyShims
  case object CLASS_NAME extends LogKeyShims
  case object CLASS_PATH extends LogKeyShims
  case object CLASS_PATHS extends LogKeyShims
  case object CLAUSES extends LogKeyShims
  case object CLEANUP_LOCAL_DIRS extends LogKeyShims
  case object CLUSTER_CENTROIDS extends LogKeyShims
  case object CLUSTER_ID extends LogKeyShims
  case object CLUSTER_LABEL extends LogKeyShims
  case object CLUSTER_LEVEL extends LogKeyShims
  case object CLUSTER_WEIGHT extends LogKeyShims
  case object CODEC_LEVEL extends LogKeyShims
  case object CODEC_NAME extends LogKeyShims
  case object CODEGEN_STAGE_ID extends LogKeyShims
  case object COLUMN_DATA_TYPE_SOURCE extends LogKeyShims
  case object COLUMN_DATA_TYPE_TARGET extends LogKeyShims
  case object COLUMN_DEFAULT_VALUE extends LogKeyShims
  case object COLUMN_NAME extends LogKeyShims
  case object COMMAND extends LogKeyShims
  case object COMMAND_OUTPUT extends LogKeyShims
  case object COMMITTED_VERSION extends LogKeyShims
  case object COMPACT_INTERVAL extends LogKeyShims
  case object COMPONENT extends LogKeyShims
  case object COMPUTE extends LogKeyShims
  case object CONFIG extends LogKeyShims
  case object CONFIG2 extends LogKeyShims
  case object CONFIG3 extends LogKeyShims
  case object CONFIG4 extends LogKeyShims
  case object CONFIG5 extends LogKeyShims
  case object CONFIG_DEPRECATION_MESSAGE extends LogKeyShims
  case object CONFIG_KEY_UPDATED extends LogKeyShims
  case object CONFIG_VERSION extends LogKeyShims
  case object CONSUMER extends LogKeyShims
  case object CONTAINER extends LogKeyShims
  case object CONTAINER_ID extends LogKeyShims
  case object CONTAINER_STATE extends LogKeyShims
  case object CONTEXT extends LogKeyShims
  case object CONTEXT_CREATION_SITE extends LogKeyShims
  case object COST extends LogKeyShims
  case object COUNT extends LogKeyShims
  case object CREATED_POOL_NAME extends LogKeyShims
  case object CREDENTIALS_RENEWAL_INTERVAL_RATIO extends LogKeyShims
  case object CROSS_VALIDATION_METRIC extends LogKeyShims
  case object CROSS_VALIDATION_METRICS extends LogKeyShims
  case object CSV_HEADER_COLUMN_NAME extends LogKeyShims
  case object CSV_HEADER_COLUMN_NAMES extends LogKeyShims
  case object CSV_HEADER_LENGTH extends LogKeyShims
  case object CSV_SCHEMA_FIELD_NAME extends LogKeyShims
  case object CSV_SCHEMA_FIELD_NAMES extends LogKeyShims
  case object CSV_SOURCE extends LogKeyShims
  case object CURRENT_BATCH_ID extends LogKeyShims
  case object CURRENT_FILE extends LogKeyShims
  case object CURRENT_MEMORY_BYTES extends LogKeyShims
  case object CURRENT_PATH extends LogKeyShims
  case object CURRENT_TIME extends LogKeyShims
  case object DATA extends LogKeyShims
  case object DATABASE_NAME extends LogKeyShims
  case object DATAFRAME_CACHE_ENTRY extends LogKeyShims
  case object DATAFRAME_ID extends LogKeyShims
  case object DATA_FILE extends LogKeyShims
  case object DATA_SOURCE extends LogKeyShims
  case object DATA_SOURCES extends LogKeyShims
  case object DEFAULT_COMPACT_INTERVAL extends LogKeyShims
  case object DEFAULT_ISOLATION_LEVEL extends LogKeyShims
  case object DEFAULT_NAME extends LogKeyShims
  case object DEFAULT_SCHEDULING_MODE extends LogKeyShims
  case object DEFAULT_VALUE extends LogKeyShims
  case object DELAY extends LogKeyShims
  case object DELEGATE extends LogKeyShims
  case object DELTA extends LogKeyShims
  case object DEPRECATED_KEY extends LogKeyShims
  case object DESCRIPTION extends LogKeyShims
  case object DESIRED_NUM_PARTITIONS extends LogKeyShims
  case object DESIRED_TREE_DEPTH extends LogKeyShims
  case object DESTINATION_PATH extends LogKeyShims
  case object DFS_FILE extends LogKeyShims
  case object DIFF_DELTA extends LogKeyShims
  case object DIVISIBLE_CLUSTER_INDICES_SIZE extends LogKeyShims
  case object DRIVER_ID extends LogKeyShims
  case object DRIVER_MEMORY_SIZE extends LogKeyShims
  case object DRIVER_STATE extends LogKeyShims
  case object DROPPED_PARTITIONS extends LogKeyShims
  case object DURATION extends LogKeyShims
  case object EARLIEST_LOADED_VERSION extends LogKeyShims
  case object EFFECTIVE_STORAGE_LEVEL extends LogKeyShims
  case object ELAPSED_TIME extends LogKeyShims
  case object ENCODING extends LogKeyShims
  case object END_INDEX extends LogKeyShims
  case object END_POINT extends LogKeyShims
  case object END_VERSION extends LogKeyShims
  case object ENGINE extends LogKeyShims
  case object EPOCH extends LogKeyShims
  case object ERROR extends LogKeyShims
  case object ESTIMATOR_PARAM_MAP extends LogKeyShims
  case object EVALUATED_FILTERS extends LogKeyShims
  case object EVENT extends LogKeyShims
  case object EVENT_LOG_DESTINATION extends LogKeyShims
  case object EVENT_LOOP extends LogKeyShims
  case object EVENT_NAME extends LogKeyShims
  case object EVENT_QUEUE extends LogKeyShims
  case object EXCEPTION extends LogKeyShims
  case object EXECUTE_INFO extends LogKeyShims
  case object EXECUTE_KEY extends LogKeyShims
  case object EXECUTION_MEMORY_SIZE extends LogKeyShims
  case object EXECUTION_PLAN_LEAVES extends LogKeyShims
  case object EXECUTOR_BACKEND extends LogKeyShims
  case object EXECUTOR_ENVS extends LogKeyShims
  case object EXECUTOR_ENV_REGEX extends LogKeyShims
  case object EXECUTOR_ID extends LogKeyShims
  case object EXECUTOR_IDS extends LogKeyShims
  case object EXECUTOR_LAUNCH_COMMANDS extends LogKeyShims
  case object EXECUTOR_MEMORY_SIZE extends LogKeyShims
  case object EXECUTOR_RESOURCES extends LogKeyShims
  case object EXECUTOR_SHUFFLE_INFO extends LogKeyShims
  case object EXECUTOR_STATE extends LogKeyShims
  case object EXECUTOR_TIMEOUT extends LogKeyShims
  case object EXEC_AMOUNT extends LogKeyShims
  case object EXISTING_FILE extends LogKeyShims
  case object EXISTING_PATH extends LogKeyShims
  case object EXIT_CODE extends LogKeyShims
  case object EXPECTED_NUM_FILES extends LogKeyShims
  case object EXPECTED_PARTITION_COLUMN extends LogKeyShims
  case object EXPIRY_TIMESTAMP extends LogKeyShims
  case object EXPR extends LogKeyShims
  case object EXPR_TERMS extends LogKeyShims
  case object EXTENDED_EXPLAIN_GENERATOR extends LogKeyShims
  case object FAILURES extends LogKeyShims
  case object FALLBACK_VERSION extends LogKeyShims
  case object FEATURE_COLUMN extends LogKeyShims
  case object FEATURE_DIMENSION extends LogKeyShims
  case object FEATURE_NAME extends LogKeyShims
  case object FETCH_SIZE extends LogKeyShims
  case object FIELD_NAME extends LogKeyShims
  case object FILE_ABSOLUTE_PATH extends LogKeyShims
  case object FILE_END_OFFSET extends LogKeyShims
  case object FILE_FORMAT extends LogKeyShims
  case object FILE_FORMAT2 extends LogKeyShims
  case object FILE_LENGTH_XATTR extends LogKeyShims
  case object FILE_MODIFICATION_TIME extends LogKeyShims
  case object FILE_NAME extends LogKeyShims
  case object FILE_NAME2 extends LogKeyShims
  case object FILE_NAME3 extends LogKeyShims
  case object FILE_START_OFFSET extends LogKeyShims
  case object FILE_SYSTEM extends LogKeyShims
  case object FILE_VERSION extends LogKeyShims
  case object FILTER extends LogKeyShims
  case object FINAL_CONTEXT extends LogKeyShims
  case object FINAL_OUTPUT_PATH extends LogKeyShims
  case object FINAL_PATH extends LogKeyShims
  case object FINISH_TRIGGER_DURATION extends LogKeyShims
  case object FROM_OFFSET extends LogKeyShims
  case object FROM_TIME extends LogKeyShims
  case object FUNCTION_NAME extends LogKeyShims
  case object FUNCTION_PARAM extends LogKeyShims
  case object GLOBAL_INIT_FILE extends LogKeyShims
  case object GLOBAL_WATERMARK extends LogKeyShims
  case object GROUP_BY_EXPRS extends LogKeyShims
  case object GROUP_ID extends LogKeyShims
  case object HADOOP_VERSION extends LogKeyShims
  case object HASH_JOIN_KEYS extends LogKeyShims
  case object HASH_MAP_SIZE extends LogKeyShims
  case object HEARTBEAT extends LogKeyShims
  case object HEARTBEAT_INTERVAL extends LogKeyShims
  case object HISTORY_DIR extends LogKeyShims
  case object HIVE_CLIENT_VERSION extends LogKeyShims
  case object HIVE_METASTORE_VERSION extends LogKeyShims
  case object HIVE_OPERATION_STATE extends LogKeyShims
  case object HIVE_OPERATION_TYPE extends LogKeyShims
  case object HOST extends LogKeyShims
  case object HOST_NAMES extends LogKeyShims
  case object HOST_PORT extends LogKeyShims
  case object HOST_PORT2 extends LogKeyShims
  case object HUGE_METHOD_LIMIT extends LogKeyShims
  case object IDENTIFIER extends LogKeyShims
  case object INCOMPATIBLE_TYPES extends LogKeyShims
  case object INDEX extends LogKeyShims
  case object INDEX_FILE extends LogKeyShims
  case object INDEX_NAME extends LogKeyShims
  case object INFERENCE_MODE extends LogKeyShims
  case object INIT extends LogKeyShims
  case object INITIAL_CAPACITY extends LogKeyShims
  case object INITIAL_HEARTBEAT_INTERVAL extends LogKeyShims
  case object INIT_MODE extends LogKeyShims
  case object INPUT extends LogKeyShims
  case object INTERVAL extends LogKeyShims
  case object ISOLATION_LEVEL extends LogKeyShims
  case object ISSUE_DATE extends LogKeyShims
  case object IS_NETWORK_REQUEST_DONE extends LogKeyShims
  case object JAR_MESSAGE extends LogKeyShims
  case object JAR_URL extends LogKeyShims
  case object JAVA_VERSION extends LogKeyShims
  case object JAVA_VM_NAME extends LogKeyShims
  case object JOB_ID extends LogKeyShims
  case object JOIN_CONDITION extends LogKeyShims
  case object JOIN_CONDITION_SUB_EXPR extends LogKeyShims
  case object JOIN_TYPE extends LogKeyShims
  case object K8S_CONTEXT extends LogKeyShims
  case object KEY extends LogKeyShims
  case object KEY2 extends LogKeyShims
  case object KEYTAB extends LogKeyShims
  case object KEYTAB_FILE extends LogKeyShims
  case object LABEL_COLUMN extends LogKeyShims
  case object LARGEST_CLUSTER_INDEX extends LogKeyShims
  case object LAST_ACCESS_TIME extends LogKeyShims
  case object LAST_VALID_TIME extends LogKeyShims
  case object LATEST_BATCH_ID extends LogKeyShims
  case object LATEST_COMMITTED_BATCH_ID extends LogKeyShims
  case object LATEST_SHUFFLE_MERGE_ID extends LogKeyShims
  case object LEARNING_RATE extends LogKeyShims
  case object LEFT_EXPR extends LogKeyShims
  case object LEFT_LOGICAL_PLAN_STATS_SIZE_IN_BYTES extends LogKeyShims
  case object LINE extends LogKeyShims
  case object LINE_NUM extends LogKeyShims
  case object LISTENER extends LogKeyShims
  case object LOADED_VERSION extends LogKeyShims
  case object LOAD_FACTOR extends LogKeyShims
  case object LOAD_TIME extends LogKeyShims
  case object LOCALE extends LogKeyShims
  case object LOCAL_SCRATCH_DIR extends LogKeyShims
  case object LOCATION extends LogKeyShims
  case object LOGICAL_PLAN_COLUMNS extends LogKeyShims
  case object LOGICAL_PLAN_LEAVES extends LogKeyShims
  case object LOG_ID extends LogKeyShims
  case object LOG_OFFSET extends LogKeyShims
  case object LOG_TYPE extends LogKeyShims
  case object LOWER_BOUND extends LogKeyShims
  case object MALFORMATTED_STRING extends LogKeyShims
  case object MAP_ID extends LogKeyShims
  case object MASTER_URL extends LogKeyShims
  case object MAX_ATTEMPTS extends LogKeyShims
  case object MAX_CACHE_UNTIL_HIGHEST_CONSUMED_SIZE extends LogKeyShims
  case object MAX_CACHE_UNTIL_LAST_PRODUCED_SIZE extends LogKeyShims
  case object MAX_CAPACITY extends LogKeyShims
  case object MAX_CATEGORIES extends LogKeyShims
  case object MAX_EXECUTOR_FAILURES extends LogKeyShims
  case object MAX_FILE_VERSION extends LogKeyShims
  case object MAX_JVM_METHOD_PARAMS_LENGTH extends LogKeyShims
  case object MAX_MEMORY_SIZE extends LogKeyShims
  case object MAX_METHOD_CODE_SIZE extends LogKeyShims
  case object MAX_NUM_BINS extends LogKeyShims
  case object MAX_NUM_CHUNKS extends LogKeyShims
  case object MAX_NUM_LOG_POLICY extends LogKeyShims
  case object MAX_NUM_PARTITIONS extends LogKeyShims
  case object MAX_NUM_POSSIBLE_BINS extends LogKeyShims
  case object MAX_NUM_ROWS_IN_MEMORY_BUFFER extends LogKeyShims
  case object MAX_SIZE extends LogKeyShims
  case object MAX_SLOTS extends LogKeyShims
  case object MAX_SPLIT_BYTES extends LogKeyShims
  case object MAX_TABLE_PARTITION_METADATA_SIZE extends LogKeyShims
  case object MEMORY_CONSUMER extends LogKeyShims
  case object MEMORY_POOL_NAME extends LogKeyShims
  case object MEMORY_SIZE extends LogKeyShims
  case object MEMORY_THRESHOLD_SIZE extends LogKeyShims
  case object MERGE_DIR_NAME extends LogKeyShims
  case object MESSAGE extends LogKeyShims
  case object METADATA_DIRECTORY extends LogKeyShims
  case object METADATA_JSON extends LogKeyShims
  case object META_FILE extends LogKeyShims
  case object METHOD_NAME extends LogKeyShims
  case object METHOD_PARAM_TYPES extends LogKeyShims
  case object METRICS_JSON extends LogKeyShims
  case object METRIC_NAME extends LogKeyShims
  case object MINI_BATCH_FRACTION extends LogKeyShims
  case object MIN_COMPACTION_BATCH_ID extends LogKeyShims
  case object MIN_NUM_FREQUENT_PATTERN extends LogKeyShims
  case object MIN_POINT_PER_CLUSTER extends LogKeyShims
  case object MIN_SHARE extends LogKeyShims
  case object MIN_SIZE extends LogKeyShims
  case object MIN_TIME extends LogKeyShims
  case object MIN_VERSION_NUM extends LogKeyShims
  case object MODEL_WEIGHTS extends LogKeyShims
  case object MODULE_NAME extends LogKeyShims
  case object NAMESPACE extends LogKeyShims
  case object NETWORK_IF extends LogKeyShims
  case object NEW_FEATURE_COLUMN_NAME extends LogKeyShims
  case object NEW_LABEL_COLUMN_NAME extends LogKeyShims
  case object NEW_PATH extends LogKeyShims
  case object NEW_RDD_ID extends LogKeyShims
  case object NEW_STATE extends LogKeyShims
  case object NEW_VALUE extends LogKeyShims
  case object NEXT_RENEWAL_TIME extends LogKeyShims
  case object NODES extends LogKeyShims
  case object NODE_LOCATION extends LogKeyShims
  case object NON_BUILT_IN_CONNECTORS extends LogKeyShims
  case object NORM extends LogKeyShims
  case object NUM_ADDED_PARTITIONS extends LogKeyShims
  case object NUM_APPS extends LogKeyShims
  case object NUM_BIN extends LogKeyShims
  case object NUM_BLOCK_IDS extends LogKeyShims
  case object NUM_BROADCAST_BLOCK extends LogKeyShims
  case object NUM_BYTES extends LogKeyShims
  case object NUM_BYTES_CURRENT extends LogKeyShims
  case object NUM_BYTES_EVICTED extends LogKeyShims
  case object NUM_BYTES_MAX extends LogKeyShims
  case object NUM_BYTES_TO_FREE extends LogKeyShims
  case object NUM_BYTES_TO_WARN extends LogKeyShims
  case object NUM_BYTES_USED extends LogKeyShims
  case object NUM_CATEGORIES extends LogKeyShims
  case object NUM_CHECKSUM_FILE extends LogKeyShims
  case object NUM_CHUNKS extends LogKeyShims
  case object NUM_CLASSES extends LogKeyShims
  case object NUM_COEFFICIENTS extends LogKeyShims
  case object NUM_COLUMNS extends LogKeyShims
  case object NUM_CONCURRENT_WRITER extends LogKeyShims
  case object NUM_CORES extends LogKeyShims
  case object NUM_DATA_FILE extends LogKeyShims
  case object NUM_DATA_FILES extends LogKeyShims
  case object NUM_DRIVERS extends LogKeyShims
  case object NUM_DROPPED_PARTITIONS extends LogKeyShims
  case object NUM_EFFECTIVE_RULE_OF_RUNS extends LogKeyShims
  case object NUM_ELEMENTS_SPILL_THRESHOLD extends LogKeyShims
  case object NUM_EVENTS extends LogKeyShims
  case object NUM_EXAMPLES extends LogKeyShims
  case object NUM_EXECUTOR_CORES extends LogKeyShims
  case object NUM_EXECUTOR_CORES_REMAINING extends LogKeyShims
  case object NUM_EXECUTOR_CORES_TOTAL extends LogKeyShims
  case object NUM_EXECUTOR_DESIRED extends LogKeyShims
  case object NUM_EXECUTOR_LAUNCH extends LogKeyShims
  case object NUM_EXECUTOR_TARGET extends LogKeyShims
  case object NUM_FAILURES extends LogKeyShims
  case object NUM_FEATURES extends LogKeyShims
  case object NUM_FILES extends LogKeyShims
  case object NUM_FILES_COPIED extends LogKeyShims
  case object NUM_FILES_FAILED_TO_DELETE extends LogKeyShims
  case object NUM_FILES_REUSED extends LogKeyShims
  case object NUM_FREQUENT_ITEMS extends LogKeyShims
  case object NUM_INDEX_FILE extends LogKeyShims
  case object NUM_INDEX_FILES extends LogKeyShims
  case object NUM_ITERATIONS extends LogKeyShims
  case object NUM_KAFKA_PULLS extends LogKeyShims
  case object NUM_KAFKA_RECORDS_PULLED extends LogKeyShims
  case object NUM_LEADING_SINGULAR_VALUES extends LogKeyShims
  case object NUM_LEFT_PARTITION_VALUES extends LogKeyShims
  case object NUM_LOADED_ENTRIES extends LogKeyShims
  case object NUM_LOCAL_DIRS extends LogKeyShims
  case object NUM_LOCAL_FREQUENT_PATTERN extends LogKeyShims
  case object NUM_MERGER_LOCATIONS extends LogKeyShims
  case object NUM_META_FILES extends LogKeyShims
  case object NUM_NODES extends LogKeyShims
  case object NUM_PARTITIONS extends LogKeyShims
  case object NUM_PARTITIONS2 extends LogKeyShims
  case object NUM_PATHS extends LogKeyShims
  case object NUM_PEERS extends LogKeyShims
  case object NUM_PEERS_REPLICATED_TO extends LogKeyShims
  case object NUM_PEERS_TO_REPLICATE_TO extends LogKeyShims
  case object NUM_PENDING_LAUNCH_TASKS extends LogKeyShims
  case object NUM_POD extends LogKeyShims
  case object NUM_POD_SHARED_SLOT extends LogKeyShims
  case object NUM_POD_TARGET extends LogKeyShims
  case object NUM_POINT extends LogKeyShims
  case object NUM_PREFIXES extends LogKeyShims
  case object NUM_PRUNED extends LogKeyShims
  case object NUM_RECORDS_READ extends LogKeyShims
  case object NUM_REMOVED_WORKERS extends LogKeyShims
  case object NUM_REPLICAS extends LogKeyShims
  case object NUM_REQUESTS extends LogKeyShims
  case object NUM_REQUEST_SYNC_TASK extends LogKeyShims
  case object NUM_RESOURCE_SLOTS extends LogKeyShims
  case object NUM_RETRIES extends LogKeyShims
  case object NUM_RETRY extends LogKeyShims
  case object NUM_RIGHT_PARTITION_VALUES extends LogKeyShims
  case object NUM_ROWS extends LogKeyShims
  case object NUM_RULE_OF_RUNS extends LogKeyShims
  case object NUM_SEQUENCES extends LogKeyShims
  case object NUM_SLOTS extends LogKeyShims
  case object NUM_SPILL_INFOS extends LogKeyShims
  case object NUM_SPILL_WRITERS extends LogKeyShims
  case object NUM_SUB_DIRS extends LogKeyShims
  case object NUM_TASKS extends LogKeyShims
  case object NUM_TASK_CPUS extends LogKeyShims
  case object NUM_TRAIN_WORD extends LogKeyShims
  case object NUM_VERSIONS_RETAIN extends LogKeyShims
  case object NUM_WEIGHTED_EXAMPLES extends LogKeyShims
  case object OBJECT_AGG_SORT_BASED_FALLBACK_THRESHOLD extends LogKeyShims
  case object OBJECT_ID extends LogKeyShims
  case object OFFSET extends LogKeyShims
  case object OFFSETS extends LogKeyShims
  case object OFFSET_SEQUENCE_METADATA extends LogKeyShims
  case object OLD_BLOCK_MANAGER_ID extends LogKeyShims
  case object OLD_GENERATION_GC extends LogKeyShims
  case object OLD_VALUE extends LogKeyShims
  case object OPEN_COST_IN_BYTES extends LogKeyShims
  case object OPERATION_HANDLE extends LogKeyShims
  case object OPERATION_HANDLE_IDENTIFIER extends LogKeyShims
  case object OPTIMIZED_PLAN_COLUMNS extends LogKeyShims
  case object OPTIMIZER_CLASS_NAME extends LogKeyShims
  case object OPTIONS extends LogKeyShims
  case object OP_ID extends LogKeyShims
  case object OP_TYPE extends LogKeyShims
  case object OS_ARCH extends LogKeyShims
  case object OS_NAME extends LogKeyShims
  case object OS_VERSION extends LogKeyShims
  case object OUTPUT extends LogKeyShims
  case object OVERHEAD_MEMORY_SIZE extends LogKeyShims
  case object PAGE_SIZE extends LogKeyShims
  case object PARSE_MODE extends LogKeyShims
  case object PARTITIONED_FILE_READER extends LogKeyShims
  case object PARTITIONER extends LogKeyShims
  case object PARTITION_ID extends LogKeyShims
  case object PARTITION_SPECIFICATION extends LogKeyShims
  case object PARTITION_SPECS extends LogKeyShims
  case object PATH extends LogKeyShims
  case object PATHS extends LogKeyShims
  case object PEER extends LogKeyShims
  case object PERCENT extends LogKeyShims
  case object PIPELINE_STAGE_UID extends LogKeyShims
  case object PLUGIN_NAME extends LogKeyShims
  case object POD_ID extends LogKeyShims
  case object POD_NAME extends LogKeyShims
  case object POD_NAMESPACE extends LogKeyShims
  case object POD_PHASE extends LogKeyShims
  case object POD_STATE extends LogKeyShims
  case object POINT_OF_CENTER extends LogKeyShims
  case object POLICY extends LogKeyShims
  case object POOL_NAME extends LogKeyShims
  case object PORT extends LogKeyShims
  case object PORT2 extends LogKeyShims
  case object POST_SCAN_FILTERS extends LogKeyShims
  case object PREDICATE extends LogKeyShims
  case object PREDICATES extends LogKeyShims
  case object PREFIX extends LogKeyShims
  case object PRETTY_ID_STRING extends LogKeyShims
  case object PRINCIPAL extends LogKeyShims
  case object PROCESS extends LogKeyShims
  case object PROCESSING_TIME extends LogKeyShims
  case object PRODUCER_ID extends LogKeyShims
  case object PROPERTY_NAME extends LogKeyShims
  case object PROTOCOL_VERSION extends LogKeyShims
  case object PROVIDER extends LogKeyShims
  case object PUSHED_FILTERS extends LogKeyShims
  case object PVC_METADATA_NAME extends LogKeyShims
  case object PYTHON_EXEC extends LogKeyShims
  case object PYTHON_PACKAGES extends LogKeyShims
  case object PYTHON_VERSION extends LogKeyShims
  case object PYTHON_WORKER_MODULE extends LogKeyShims
  case object PYTHON_WORKER_RESPONSE extends LogKeyShims
  case object QUERY_CACHE_VALUE extends LogKeyShims
  case object QUERY_HINT extends LogKeyShims
  case object QUERY_ID extends LogKeyShims
  case object QUERY_PLAN extends LogKeyShims
  case object QUERY_PLAN_COMPARISON extends LogKeyShims
  case object QUERY_PLAN_LENGTH_ACTUAL extends LogKeyShims
  case object QUERY_PLAN_LENGTH_MAX extends LogKeyShims
  case object QUERY_RUN_ID extends LogKeyShims
  case object RANGE extends LogKeyShims
  case object RDD_CHECKPOINT_DIR extends LogKeyShims
  case object RDD_DEBUG_STRING extends LogKeyShims
  case object RDD_DESCRIPTION extends LogKeyShims
  case object RDD_ID extends LogKeyShims
  case object READ_LIMIT extends LogKeyShims
  case object REASON extends LogKeyShims
  case object REATTACHABLE extends LogKeyShims
  case object RECEIVED_BLOCK_INFO extends LogKeyShims
  case object RECEIVED_BLOCK_TRACKER_LOG_EVENT extends LogKeyShims
  case object RECEIVER_ID extends LogKeyShims
  case object RECEIVER_IDS extends LogKeyShims
  case object RECORDS extends LogKeyShims
  case object RECOVERY_STATE extends LogKeyShims
  case object REDACTED_STATEMENT extends LogKeyShims
  case object REDUCE_ID extends LogKeyShims
  case object REGISTERED_EXECUTOR_FILE extends LogKeyShims
  case object RELATION_NAME extends LogKeyShims
  case object RELATION_OUTPUT extends LogKeyShims
  case object RELATIVE_TOLERANCE extends LogKeyShims
  case object REMAINING_PARTITIONS extends LogKeyShims
  case object REMOTE_ADDRESS extends LogKeyShims
  case object REMOVE_FROM_MASTER extends LogKeyShims
  case object REPORT_DETAILS extends LogKeyShims
  case object REQUESTER_SIZE extends LogKeyShims
  case object REQUEST_ID extends LogKeyShims
  case object RESOURCE extends LogKeyShims
  case object RESOURCE_NAME extends LogKeyShims
  case object RESOURCE_PROFILE_ID extends LogKeyShims
  case object RESOURCE_PROFILE_IDS extends LogKeyShims
  case object RESOURCE_PROFILE_TO_TOTAL_EXECS extends LogKeyShims
  case object RESPONSE_BODY_SIZE extends LogKeyShims
  case object RESULT extends LogKeyShims
  case object RESULT_SIZE_BYTES extends LogKeyShims
  case object RESULT_SIZE_BYTES_MAX extends LogKeyShims
  case object RETRY_INTERVAL extends LogKeyShims
  case object RETRY_WAIT_TIME extends LogKeyShims
  case object RIGHT_EXPR extends LogKeyShims
  case object RIGHT_LOGICAL_PLAN_STATS_SIZE_IN_BYTES extends LogKeyShims
  case object RMSE extends LogKeyShims
  case object ROCKS_DB_LOG_LEVEL extends LogKeyShims
  case object ROCKS_DB_LOG_MESSAGE extends LogKeyShims
  case object RPC_ADDRESS extends LogKeyShims
  case object RPC_ENDPOINT_REF extends LogKeyShims
  case object RPC_MESSAGE_CAPACITY extends LogKeyShims
  case object RULE_NAME extends LogKeyShims
  case object RUN_ID extends LogKeyShims
  case object SCALA_VERSION extends LogKeyShims
  case object SCHEDULER_POOL_NAME extends LogKeyShims
  case object SCHEMA extends LogKeyShims
  case object SCHEMA2 extends LogKeyShims
  case object SERVER_NAME extends LogKeyShims
  case object SERVICE_NAME extends LogKeyShims
  case object SERVLET_CONTEXT_HANDLER_PATH extends LogKeyShims
  case object SESSION_HANDLE extends LogKeyShims
  case object SESSION_HOLD_INFO extends LogKeyShims
  case object SESSION_ID extends LogKeyShims
  case object SESSION_KEY extends LogKeyShims
  case object SET_CLIENT_INFO_REQUEST extends LogKeyShims
  case object SHARD_ID extends LogKeyShims
  case object SHELL_OPTIONS extends LogKeyShims
  case object SHORT_USER_NAME extends LogKeyShims
  case object SHUFFLE_BLOCK_INFO extends LogKeyShims
  case object SHUFFLE_DB_BACKEND_KEY extends LogKeyShims
  case object SHUFFLE_DB_BACKEND_NAME extends LogKeyShims
  case object SHUFFLE_ID extends LogKeyShims
  case object SHUFFLE_MERGE_ID extends LogKeyShims
  case object SHUFFLE_MERGE_RECOVERY_FILE extends LogKeyShims
  case object SHUFFLE_SERVICE_CONF_OVERLAY_URL extends LogKeyShims
  case object SHUFFLE_SERVICE_METRICS_NAMESPACE extends LogKeyShims
  case object SHUFFLE_SERVICE_NAME extends LogKeyShims
  case object SIGMAS_LENGTH extends LogKeyShims
  case object SIGNAL extends LogKeyShims
  case object SIZE extends LogKeyShims
  case object SLEEP_TIME extends LogKeyShims
  case object SLIDE_DURATION extends LogKeyShims
  case object SMALLEST_CLUSTER_INDEX extends LogKeyShims
  case object SNAPSHOT_VERSION extends LogKeyShims
  case object SOCKET_ADDRESS extends LogKeyShims
  case object SOURCE_PATH extends LogKeyShims
  case object SPARK_BRANCH extends LogKeyShims
  case object SPARK_BUILD_DATE extends LogKeyShims
  case object SPARK_BUILD_USER extends LogKeyShims
  case object SPARK_DATA_STREAM extends LogKeyShims
  case object SPARK_PLAN_ID extends LogKeyShims
  case object SPARK_REPO_URL extends LogKeyShims
  case object SPARK_REVISION extends LogKeyShims
  case object SPARK_VERSION extends LogKeyShims
  case object SPILL_TIMES extends LogKeyShims
  case object SQL_TEXT extends LogKeyShims
  case object SRC_PATH extends LogKeyShims
  case object STAGE_ATTEMPT extends LogKeyShims
  case object STAGE_ID extends LogKeyShims
  case object START_INDEX extends LogKeyShims
  case object STATEMENT_ID extends LogKeyShims
  case object STATE_STORE_ID extends LogKeyShims
  case object STATE_STORE_PROVIDER extends LogKeyShims
  case object STATE_STORE_VERSION extends LogKeyShims
  case object STATUS extends LogKeyShims
  case object STDERR extends LogKeyShims
  case object STOP_SITE_SHORT_FORM extends LogKeyShims
  case object STORAGE_LEVEL extends LogKeyShims
  case object STORAGE_LEVEL_DESERIALIZED extends LogKeyShims
  case object STORAGE_LEVEL_REPLICATION extends LogKeyShims
  case object STORAGE_MEMORY_SIZE extends LogKeyShims
  case object STORE_ID extends LogKeyShims
  case object STREAMING_DATA_SOURCE_DESCRIPTION extends LogKeyShims
  case object STREAMING_DATA_SOURCE_NAME extends LogKeyShims
  case object STREAMING_OFFSETS_END extends LogKeyShims
  case object STREAMING_OFFSETS_START extends LogKeyShims
  case object STREAMING_QUERY_PROGRESS extends LogKeyShims
  case object STREAMING_SOURCE extends LogKeyShims
  case object STREAMING_TABLE extends LogKeyShims
  case object STREAMING_WRITE extends LogKeyShims
  case object STREAM_CHUNK_ID extends LogKeyShims
  case object STREAM_ID extends LogKeyShims
  case object STREAM_NAME extends LogKeyShims
  case object SUBMISSION_ID extends LogKeyShims
  case object SUBSAMPLING_RATE extends LogKeyShims
  case object SUB_QUERY extends LogKeyShims
  case object TABLE_NAME extends LogKeyShims
  case object TABLE_TYPE extends LogKeyShims
  case object TABLE_TYPES extends LogKeyShims
  case object TARGET_NUM_EXECUTOR extends LogKeyShims
  case object TARGET_NUM_EXECUTOR_DELTA extends LogKeyShims
  case object TARGET_PATH extends LogKeyShims
  case object TASK_ATTEMPT_ID extends LogKeyShims
  case object TASK_ID extends LogKeyShims
  case object TASK_NAME extends LogKeyShims
  case object TASK_REQUIREMENTS extends LogKeyShims
  case object TASK_SET_NAME extends LogKeyShims
  case object TASK_STATE extends LogKeyShims
  case object TEMP_FILE extends LogKeyShims
  case object TEMP_OUTPUT_PATH extends LogKeyShims
  case object TEMP_PATH extends LogKeyShims
  case object TEST_SIZE extends LogKeyShims
  case object THREAD extends LogKeyShims
  case object THREAD_ID extends LogKeyShims
  case object THREAD_NAME extends LogKeyShims
  case object THREAD_POOL_KEEPALIVE_TIME extends LogKeyShims
  case object THREAD_POOL_SIZE extends LogKeyShims
  case object THREAD_POOL_WAIT_QUEUE_SIZE extends LogKeyShims
  case object THRESHOLD extends LogKeyShims
  case object TID extends LogKeyShims
  case object TIME extends LogKeyShims
  case object TIMEOUT extends LogKeyShims
  case object TIMER extends LogKeyShims
  case object TIMESTAMP extends LogKeyShims
  case object TIME_UNITS extends LogKeyShims
  case object TIP extends LogKeyShims
  case object TOKEN extends LogKeyShims
  case object TOKEN_KIND extends LogKeyShims
  case object TOKEN_REGEX extends LogKeyShims
  case object TOKEN_RENEWER extends LogKeyShims
  case object TOPIC extends LogKeyShims
  case object TOPIC_PARTITION extends LogKeyShims
  case object TOPIC_PARTITIONS extends LogKeyShims
  case object TOPIC_PARTITION_OFFSET extends LogKeyShims
  case object TOPIC_PARTITION_OFFSET_RANGE extends LogKeyShims
  case object TOTAL extends LogKeyShims
  case object TOTAL_EFFECTIVE_TIME extends LogKeyShims
  case object TOTAL_TIME extends LogKeyShims
  case object TOTAL_TIME_READ extends LogKeyShims
  case object TO_TIME extends LogKeyShims
  case object TRAINING_SIZE extends LogKeyShims
  case object TRAIN_VALIDATION_SPLIT_METRIC extends LogKeyShims
  case object TRAIN_VALIDATION_SPLIT_METRICS extends LogKeyShims
  case object TRANSFER_TYPE extends LogKeyShims
  case object TREE_NODE extends LogKeyShims
  case object TRIGGER_INTERVAL extends LogKeyShims
  case object UI_FILTER extends LogKeyShims
  case object UI_FILTER_PARAMS extends LogKeyShims
  case object UI_PROXY_BASE extends LogKeyShims
  case object UNKNOWN_PARAM extends LogKeyShims
  case object UNSUPPORTED_EXPR extends LogKeyShims
  case object UNSUPPORTED_HINT_REASON extends LogKeyShims
  case object UNTIL_OFFSET extends LogKeyShims
  case object UPPER_BOUND extends LogKeyShims
  case object URI extends LogKeyShims
  case object URIS extends LogKeyShims
  case object URL extends LogKeyShims
  case object URL2 extends LogKeyShims
  case object USER_ID extends LogKeyShims
  case object USER_NAME extends LogKeyShims
  case object UUID extends LogKeyShims
  case object VALUE extends LogKeyShims
  case object VERSION_NUM extends LogKeyShims
  case object VIRTUAL_CORES extends LogKeyShims
  case object VOCAB_SIZE extends LogKeyShims
  case object WAIT_RESULT_TIME extends LogKeyShims
  case object WAIT_SEND_TIME extends LogKeyShims
  case object WATERMARK_CONSTRAINT extends LogKeyShims
  case object WEB_URL extends LogKeyShims
  case object WEIGHT extends LogKeyShims
  case object WORKER extends LogKeyShims
  case object WORKER_HOST extends LogKeyShims
  case object WORKER_ID extends LogKeyShims
  case object WORKER_PORT extends LogKeyShims
  case object WORKER_URL extends LogKeyShims
  case object WRITE_AHEAD_LOG_INFO extends LogKeyShims
  case object WRITE_JOB_UUID extends LogKeyShims
  case object XML_SCHEDULING_MODE extends LogKeyShims
  case object XSD_PATH extends LogKeyShims
  case object YOUNG_GENERATION_GC extends LogKeyShims
}
